import MizeCelebration from './MizeCelebration';
import MizeMascot from './MizeMascot';
import React,{useEffect,useRef,useState} from 'react';
import {AccessibilityInfo,BackHandler,findNodeHandle,Image,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import Slider from '@react-native-community/slider';
import {goals,genders,activities,macroKeys,type PersonalProfile} from './personal-profile';
import {usePersonalFlow,titles,tips} from './use-personal-flow';
export default function PersonalOnboarding({initial,start=0,onSave,onExit,onFinish}:{initial:PersonalProfile|null;start?:number;onSave:(p:PersonalProfile)=>Promise<boolean>;onExit:()=>void;onFinish:()=>void}) {
 const f=usePersonalFlow(initial,start,onSave,onExit),scroll=useRef<ScrollView>(null),heading=useRef<Text>(null);
 useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});const tag=findNodeHandle(heading.current);if(tag)AccessibilityInfo.setAccessibilityFocus(tag);},[f.step,f.done]);
 useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(!f.done)f.back();else onFinish();return true;});return()=>sub.remove();});
 const options=f.step===6?activities:[];
 const key='activity',numeric=f.step===1?'age':'weight';
 const button=(label:string,action:()=>void,secondary=false)=><Pressable accessibilityRole="button" accessibilityState={{disabled:f.saving}} disabled={f.saving} onPress={action} style={[s.button,secondary&&s.secondary]}><Text style={[s.buttonText,secondary&&s.ink]}>{label}</Text></Pressable>;
 return <View style={s.root}><ScrollView ref={scroll} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {f.done?<View style={s.celebrate}><Text style={s.sparkles} accessibilityElementsHidden>✦ · ✧ · ✦</Text><MizeCelebration/><Text ref={heading} accessibilityRole="header" style={s.title}>You’re all set!</Text><Text style={s.body}>Let’s find a meal near you that fits.</Text><Text style={s.body}>You can change your goal and macros anytime in your profile.</Text></View>:<>
 <View style={s.between}>{button('← Back',f.back,true)}<Text style={s.body}>Step {f.step+1} of 9</Text></View><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:9,now:f.step+1}} style={s.track}><View style={[s.fill,{width:`${(f.step+1)/9*100}%`}]}/></View>
 <Text style={s.eyebrow}>A LITTLE ABOUT YOU</Text><Text ref={heading} accessibilityRole="header" style={s.title}>{titles[f.step]}</Text><View style={s.guide}><MizeMascot key={f.step} style={s.mize}/><Text style={[s.body,{flex:1}]}>{tips[f.step]}</Text></View>
 <View style={s.options}>{options.map(v=><Pressable key={v} accessibilityRole="button" accessibilityState={{selected:f.answers[key]===v}} disabled={f.saving} onPress={()=>f.answer(key,v)} style={[s.option,f.answers[key]===v&&s.selected]}><Text style={s.choice}>{v}</Text><Text style={s.choice}>{f.answers[key]===v?'✓':'↗'}</Text></Pressable>)}</View>
 {[0,2].includes(f.step)&&<Dropdown label={f.step===0?'Goal':'Gender'} value={f.step===0?f.answers.goal:f.answers.sex} options={f.step===0?goals:genders} disabled={f.saving} onSelect={v=>f.answer(f.step===0?'goal':'sex',v)}/>}
 {[3,5].includes(f.step)&&<View style={s.options}><Text style={s.body}>{f.step===3?'Height in cm':'days per week'}</Text><Text style={s.value}>{f.step===3?f.answers.height:f.answers.trainingDays}{f.step===3?' cm':f.answers.trainingDays===1?' day':' days'}</Text><Slider disabled={f.saving} accessibilityLabel={f.step===3?'Height in cm':'days per week'} minimumValue={f.step===3?100:1} maximumValue={f.step===3?250:7} step={1} value={f.step===3?f.answers.height:f.answers.trainingDays} onValueChange={v=>f.answer(f.step===3?'height':'trainingDays',v)} minimumTrackTintColor="#073D2B" thumbTintColor="#073D2B"/><View style={s.between}><Text style={s.body}>{f.step===3?'100 cm':'1 day'}</Text><Text style={s.body}>{f.step===3?'250 cm':'7 days'}</Text></View></View>}
 {[1,4].includes(f.step)&&<View style={s.number}><Text style={s.body}>{numeric==='age'?'your age in years':'Weight in kg'}</Text><View style={s.between}><TextInput editable={!f.saving} accessibilityLabel={numeric} keyboardType={numeric==='age'?'number-pad':'decimal-pad'} value={f.answers[numeric]===undefined?'':String(f.answers[numeric])} onChangeText={v=>f.answer(numeric,v===''?undefined:Number(v.replace(',','.')))} style={s.regularInput}/><Text style={s.body}>{numeric==='age'?'years':'kg'}</Text></View></View>}
 {f.step===7&&f.daily&&<View style={s.macros}>{macroKeys.map(k=><View key={k} style={s.macro}><Text style={s.body}>{k==='calories'?'Calories':k[0].toUpperCase()+k.slice(1)}</Text><TextInput accessibilityLabel={`Daily ${k}`} keyboardType="decimal-pad" value={Number.isNaN(f.daily![k])?'':String(Math.round(f.daily![k]))} onChangeText={v=>f.setDaily({...f.daily!,[k]:v===''?NaN:Number(v.replace(',','.'))})} style={s.input}/><Text style={s.body}>{k==='calories'?'kcal':'g'}</Text></View>)}</View>}
 {f.step===8&&f.daily&&<><View style={s.options}>{[{label:'Small meal',hint:'A light bite',value:.2},{label:'Regular meal',hint:'A typical lunch',value:1/3},{label:'Large meal',hint:'Your biggest meal',value:.5}].map(p=><Pressable key={p.label} accessibilityRole="button" accessibilityState={{selected:Math.abs(f.share-p.value)<.001}} disabled={f.saving} onPress={()=>f.setShare(p.value)} style={[s.option,Math.abs(f.share-p.value)<.001&&s.selected]}><View><Text style={s.choice}>{p.label}</Text><Text style={s.body}>{p.hint} · {Math.round(p.value*100)}%</Text></View></Pressable>)}</View><Text style={s.share}>{Math.round(f.share*100)}% <Text style={s.body}>of your day</Text></Text><Slider disabled={f.saving} accessibilityLabel="Share of daily macros for this meal" accessibilityValue={{min:10,max:100,now:Math.round(f.share*100)}} minimumValue={.1} maximumValue={1} value={f.share} onValueChange={f.setShare} minimumTrackTintColor="#073D2B" thumbTintColor="#073D2B"/><View style={s.between}><Text style={s.body}>Small meal</Text><Text style={s.body}>Main meal</Text></View>{button('Use a third',()=>f.setShare(1/3),true)}<View style={s.macros}>{macroKeys.map(k=><View key={k} style={s.macro}><Text style={s.value}>{Math.round(f.daily![k]*f.share)}</Text><Text style={s.body}>{k==='calories'?'kcal':`${k} · g`}</Text></View>)}</View></>}
 {f.error&&<Text accessibilityRole="alert" accessibilityLiveRegion="polite" style={s.error}>{f.error}</Text>}
 </>}
 </ScrollView><View style={s.footer}>{button(f.done?'Find my meals →':f.saving?'Saving…':f.step===8?'Use these macros →':'Continue →',f.done?onFinish:()=>void f.next())}<Text style={[s.body,{textAlign:'center',fontSize:12}]}>You can change this anytime.</Text></View></View>;
}
function Dropdown({label,value,options,disabled,onSelect}:{label:string;value?:string;options:readonly string[];disabled:boolean;onSelect:(value:string)=>void}) {
 const [open,setOpen]=useState(false);
 return <View style={s.options}><Text style={s.body}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{expanded:open,disabled}} disabled={disabled} onPress={()=>setOpen(true)} style={s.option}><Text style={s.body}>{value??('Choose your '+label.toLowerCase())}</Text><Text style={s.body}>⌄</Text></Pressable><Modal transparent visible={open} animationType="none" onRequestClose={()=>setOpen(false)}><View style={s.menuBackdrop}><View accessibilityViewIsModal style={s.menu}><Text accessibilityRole="header" style={s.choice}>{label}</Text><ScrollView>{options.map(v=><Pressable key={v} accessibilityRole="radio" accessibilityState={{checked:v===value}} onPress={()=>{onSelect(v);setOpen(false);}} style={[s.option,v===value&&s.selected]}><Text style={s.body}>{v}</Text><Text>{v===value?'✓':''}</Text></Pressable>)}</ScrollView><Pressable accessibilityRole="button" onPress={()=>setOpen(false)} style={s.secondary}><Text style={s.body}>Cancel</Text></Pressable></View></View></Modal></View>;
}
const s=StyleSheet.create({regularInput:{fontSize:16,fontWeight:'400',color:'#073D2B',minHeight:54,flex:1},menuBackdrop:{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(0,0,0,0.3)'},menu:{backgroundColor:'#F7F8F3',padding:20,borderRadius:22,gap:14,maxHeight:'80%'},root:{flex:1,backgroundColor:'#F7F8F3'},content:{padding:24,paddingBottom:30},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},track:{height:5,borderRadius:4,backgroundColor:'#E0E7D9',marginVertical:18},fill:{height:5,backgroundColor:'#073D2B',borderRadius:4},eyebrow:{color:'#617153',fontSize:11,letterSpacing:2,fontWeight:'700',marginTop:20,marginBottom:12},title:{fontSize:34,lineHeight:39,fontWeight:'700',color:'#073D2B',letterSpacing:-1},body:{fontSize:16,lineHeight:24,color:'#53604E'},guide:{flexDirection:'row',alignItems:'center',gap:14,marginVertical:24},mize:{width:80,height:98,resizeMode:'contain'},options:{gap:10},option:{padding:18,borderRadius:18,borderWidth:1,borderColor:'#DFE5D6',backgroundColor:'white',flexDirection:'row',justifyContent:'space-between'},selected:{backgroundColor:'#D1EE75',borderColor:'#073D2B'},choice:{fontSize:17,fontWeight:'600',color:'#073D2B'},number:{backgroundColor:'white',borderRadius:22,padding:22},input:{fontSize:32,fontWeight:'600',color:'#073D2B',minWidth:80,minHeight:54,flexShrink:1},macros:{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:18},macro:{width:'47%',backgroundColor:'white',padding:16,borderRadius:20},value:{fontSize:29,color:'#073D2B',fontWeight:'700'},share:{fontSize:48,color:'#073D2B',fontWeight:'700',marginVertical:12},footer:{padding:18,paddingBottom:28,gap:8,borderTopWidth:1,borderColor:'#E0E7D9',backgroundColor:'#F7F8F3'},button:{backgroundColor:'#073D2B',padding:17,borderRadius:30,alignItems:'center',minHeight:48},buttonText:{color:'white',fontSize:16,fontWeight:'700'},secondary:{backgroundColor:'transparent'},ink:{color:'#073D2B'},error:{color:'#9A3027',padding:15,backgroundColor:'#FFF0E6',borderRadius:12},celebrate:{alignItems:'center',gap:20,paddingVertical:35},hero:{width:180,height:200,resizeMode:'contain'},sparkles:{fontSize:40,color:'#83A843'}});
