import DishIllustration from './src/DishIllustration';
import AvocadoScore from './src/AvocadoScore';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, AppState, BackHandler, Image, Keyboard, KeyboardAvoidingView, Linking, Platform, Pressable, ScrollView, Switch, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as ExpoLocation from 'expo-location';
import FindMeals from './src/FindMeals';
import Slider from '@react-native-community/slider';
import { defaults, intents, openingInfo, simplifyTargets, rankSimpleMeals as rankMeals, validateTargets, type Targets, type Meal, type Match } from './src/domain';
import { loadPreferences, savePreferences } from './src/storage';
import { catalog, curatedCatalog } from './src/catalog';
import { loadMobileCatalog } from './src/catalog-client';
import { activityStats, chooseMeal, emptyActivity, newId, restaurantKey, removeHistoryEntry, updateHistory, type Activity, type HistoryEntry } from './src/activity';
import { AdvancedTargets, HistoryScreen, MenuCapture, ReportScreen } from './src/FeatureScreens';
import { deleteOwnedPhotos, deletePhotoCopy, exportRecords } from './src/photos';

type Screen = 'Loading' | 'SearchMethod' | 'Home' | 'Targets' | 'Help' | 'Map' | 'Saved' | 'Profile' | 'Meal' | 'History' | 'Menu' | 'Report' | 'Privacy' | 'Support';
type Place = { lat: number; lon: number; name: string };
type IconName = React.ComponentProps<typeof Ionicons>['name'];
const C = { bg: '#F7F8F3', green: '#073D2B', ink: '#101C21', muted: '#6C786A', lime: '#D1EE75', line: '#E0E7D9', soft: '#EDF2E6', white: '#FFFFFF' };
const mascot = require('./assets/mize.png');
const navigation: { name: Screen; icon: IconName; active: IconName }[] = [
  {name:'Map',icon:'map-outline',active:'map'}, {name:'Saved',icon:'heart-outline',active:'heart'}, {name:'Profile',icon:'person-outline',active:'person'}
];
function Icon({name,size=22,color=C.green}:{name:IconName;size?:number;color?:string}) { return <Ionicons name={name} size={size} color={color}/>; }
function Button({title,onPress,secondary=false,disabled=false,icon}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:IconName}) { return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary?s.secondary:s.primary,disabled&&s.disabled,pressed&&s.pressed]}><Text style={[s.buttonText,secondary&&{color:C.green}]}>{title}</Text>{icon&&<Icon name={icon} size={19} color={secondary?C.green:C.white}/>}</Pressable>; }
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}) { return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[s.chip,selected&&s.chipSelected]}><Text style={[s.chipText,selected&&{color:C.white}]}>{label}</Text></Pressable>; }
function Empty({icon,title,body,action}:{icon:IconName;title:string;body:string;action?:React.ReactNode}) { return <View style={s.empty}><Icon name={icon} size={32}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.body}>{body}</Text>{action}</View>; }

function MacroMize() {
 const {height:windowHeight,width:windowWidth}=useWindowDimensions();
 const compact=windowHeight<860||windowWidth<375;
 const [screen,setScreen]=useState<Screen>('Loading');
 const [onboardingCompleted,setOnboardingCompleted]=useState(false);
 const [committed,setCommitted]=useState<Targets>(defaults);
 const [targetBack,setTargetBack]=useState<Screen>('SearchMethod');
 const [finderLayout,setFinderLayout]=useState<'map'|'list'>('map');
 const [mealBack,setMealBack]=useState<Screen>('Map');
 const manualStarted=useRef(false);
 const autoLocated=useRef(false);
 const locatingRef=useRef(false);
 const [targets,setTargets]=useState<Targets>(defaults);
 const [calories,setCalories]=useState(String(defaults.calories));
 const [protein,setProtein]=useState(String(defaults.protein));
 const [exclusions,setExclusions]=useState('');
 const [saved,setSaved]=useState<string[]>([]);
 const [activity,setActivity]=useState<Activity>(emptyActivity);
 const [savedView,setSavedView]=useState<'Meals'|'Restaurants'>('Meals');
 const [reportMeal,setReportMeal]=useState<Meal|null>(null);
 const [restaurantCatalog,setRestaurantCatalog]=useState<Meal[]>(catalog);
 const [catalogStatus,setCatalogStatus]=useState('snapshot');
 useEffect(()=>{const controller=new AbortController();void loadMobileCatalog(process.env.EXPO_PUBLIC_CATALOG_API_URL,catalog,curatedCatalog,controller.signal).then(result=>{if(!controller.signal.aborted){setRestaurantCatalog(result.meals);setCatalogStatus(result.status);}});return()=>controller.abort();},[]);
 const meals=[...restaurantCatalog,...activity.importedMeals];
 const hasMeals=meals.length>0;
 const stats=activityStats(activity,saved);
 const [ready,setReady]=useState(false);
 const [saving,setSaving]=useState(false);
 const [message,setMessage]=useState('');
 const [selectedIntent,setSelectedIntent]=useState<number|null>(null);
 const [goal,setGoal]=useState('');
 const [place,setPlace]=useState<Place|null>({lat:53.5503,lon:9.9920,name:'Hamburg Zentrum · launch area'});
 const [area,setArea]=useState('');
 const [locating,setLocating]=useState(false);
 const [locationStatus,setLocationStatus]=useState('Not requested');
 const [locationError,setLocationError]=useState('');
 const [previewId,setPreviewId]=useState<string|null>(null);
 const [selectedMeal,setSelectedMeal]=useState<Meal|null>(null);

 const scrollRef=useRef<ScrollView|null>(null);
 const dirty=useRef(false);
 const searchAbort=useRef<AbortController|null>(null);
 const lastSearch=useRef(0);
 const savingRef=useRef(false);
 useEffect(()=>{void restore();return()=>searchAbort.current?.abort();},[]);
 useEffect(()=>{scrollRef.current?.scrollTo({y:0,animated:false});const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(screen==='Home'||screen==='Map'||screen==='Loading')return false;go(screen==='Meal'?mealBack:screen==='Targets'?targetBack:screen==='Help'?'SearchMethod':screen==='SearchMethod'?'Home':onboardingCompleted?'Map':'Home');return true;});return()=>sub.remove();},[screen,mealBack,targetBack,onboardingCompleted]);

 async function restore(){try{const state=await loadPreferences();state.targets=simplifyTargets(state.targets);if(!dirty.current){setTargets(state.targets);setCalories(String(state.targets.calories));setProtein(String(state.targets.protein));setExclusions(state.targets.exclusions.join(', '));}setSaved(state.saved);setActivity(state.activity);setCommitted(state.targets);setOnboardingCompleted(state.onboardingCompleted);setScreen(state.onboardingCompleted?'Map':'Home');setReady(true);setMessage('');}catch(e){setReady(false);setScreen('Loading');setMessage('Your saved preferences couldn’t be loaded. Your existing data has been kept. Please retry.');}}
 function go(next:Screen){Keyboard.dismiss();if(onboardingCompleted&&next==='Targets'){setTargets({...committed,mode:'numeric'});setCalories(String(committed.calories));setProtein(String(committed.protein));setExclusions(committed.exclusions.join(', '));setTargetBack('Map');}setMessage('');setScreen(next);}
 function startManual(){if(!manualStarted.current){setTargets({...defaults});setCalories('');setProtein('');setExclusions('');manualStarted.current=true;}setTargetBack('SearchMethod');go('Targets');}
 function startHelp(){setTargetBack('Help');go('Help');}
 function edit<K extends keyof Targets>(key:K,value:Targets[K]){dirty.current=true;setTargets(t=>({...t,[key]:value}));}
 function formTargets(){return validateTargets({...targets,calories:calories.trim()?Number(calories):NaN,protein:protein.trim()?Number(protein):NaN,exclusions:[...new Set(exclusions.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean))]});}
 async function persist(next:Targets,nextSaved=saved,nextActivity=activity,complete=onboardingCompleted){next=simplifyTargets(next);if(!ready){setMessage('Please retry loading preferences in Profile before saving.');return false;}if(savingRef.current)return false;savingRef.current=true;setSaving(true);try{await savePreferences({targets:next,saved:nextSaved,activity:nextActivity,onboardingCompleted:complete});setCommitted(next);setOnboardingCompleted(complete);setTargets(next);setSaved(nextSaved);setActivity(nextActivity);return true;}catch{setMessage('We couldn’t save your changes. Your inputs are still here. Please try again.');return false;}finally{savingRef.current=false;setSaving(false);}}
 async function submitTargets(profile=false){try{const next={...formTargets(),mode:"numeric" as const};Keyboard.dismiss();if(await persist(next,saved,activity,true)){setMessage(profile?'Your preferences are saved on this device.':'');if(!profile){setScreen('Map');}}}catch(e){setMessage(e instanceof Error?e.message:'Please check your targets.');}}
 function chooseIntent(index:number){dirty.current=true;setSelectedIntent(index);const i=intents[index];setTargets(t=>({...t,mode:'numeric',goal:i.title,calories:i.calories,protein:i.protein}));setCalories(String(i.calories));setProtein(String(i.protein));setMessage('');}
 function helpFromWords(){const value=goal.toLowerCase();const i=/workout|training|sport/.test(value)?0:/protein|eiwei/.test(value)?1:/light|leicht|weniger/.test(value)?2:/full|satt/.test(value)?3:/muscle|muskel/.test(value)?4:/dinner|abend/.test(value)?5:-1;if(i<0){setMessage('Choose the direction that best describes your goal below. All targets can be adjusted.');return;}chooseIntent(i);Keyboard.dismiss();setMessage('Suggested direction selected. Review your targets next.');}
 async function locate(){
  if(locatingRef.current)return;locatingRef.current=true;setLocating(true);setLocationError('');
  let timer:ReturnType<typeof setTimeout>|undefined;
  try{let permission=await ExpoLocation.getForegroundPermissionsAsync();
   if(permission.status==='undetermined')permission=await ExpoLocation.requestForegroundPermissionsAsync();
   setLocationStatus(permission.status==='granted'?'Allowed':'Not allowed');
   if(permission.status!=='granted'){setLocationError('Location is off. Enter an area instead, or enable access in Settings.');return;}
   const point=await Promise.race([ExpoLocation.getCurrentPositionAsync({accuracy:ExpoLocation.Accuracy.Balanced}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Location timed out')),12000);})]);
   setPlace({lat:point.coords.latitude,lon:point.coords.longitude,name:'Your current location'});
  }catch{setLocationError('We couldn’t find your location. Please enter an area instead.');}
  finally{if(timer)clearTimeout(timer);locatingRef.current=false;setLocating(false);}
 }
 useEffect(()=>{if(onboardingCompleted&&screen==='Map'&&!autoLocated.current){autoLocated.current=true;void locate();}},[onboardingCompleted,screen]);
 useEffect(()=>{if(!onboardingCompleted)return;let previous=AppState.currentState;const sub=AppState.addEventListener('change',next=>{if(next==='active'&&previous==='background'){setScreen('Map');void ExpoLocation.getForegroundPermissionsAsync().then(p=>{if(p.status==='granted')void locate();}).catch(()=>{});}previous=next;});return()=>sub.remove();},[onboardingCompleted]);
 async function findArea(){if(!area.trim()||locating||Date.now()-lastSearch.current<1200)return;lastSearch.current=Date.now();searchAbort.current?.abort();const controller=new AbortController();searchAbort.current=controller;const timer=setTimeout(()=>controller.abort(),12000);setLocating(true);setLocationError('');Keyboard.dismiss();try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(area.trim())}`,{headers:{'Accept':'application/json','User-Agent':'MacroMize/1.0 (local Expo preview)'},signal:controller.signal});if(!response.ok)throw new Error();const data=await response.json() as {lat:string;lon:string;display_name:string}[];if(!Array.isArray(data)||!data.length){setLocationError('No area found. Try a city or a more specific address.');return;}const lat=Number(data[0].lat),lon=Number(data[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Error();setPlace({lat,lon,name:data[0].display_name});}catch{setLocationError('Area search is unavailable. Try again or use your location.');}finally{clearTimeout(timer);setLocating(false);}}
 let allMatches:Match[]=[];try{allMatches=place?rankMeals(meals,committed,place):[];}catch{/* A partially entered filter is validated when the user submits. */}
 const matches=allMatches;
 const preview=matches.find(meal=>meal.id===previewId)??matches[0];
 const detailMatch=selectedMeal?allMatches.find(m=>m.id===selectedMeal.id):undefined;
 function openMeal(meal:Meal){setMealBack(screen);setSelectedMeal(meal);go('Meal');}
 async function toggleSaved(meal:Meal|null=selectedMeal){if(!meal)return;const next=saved.includes(meal.id)?saved.filter(id=>id!==meal.id):[...saved,meal.id];if(await persist(committed,next))setMessage(next.includes(meal.id)?'Saved on this device.':'Removed from Saved.');}
 async function openLink(url:string){try{await Linking.openURL(url);}catch{Alert.alert('Couldn’t open the link','Please try again.');}}
 function nutritionLabel(meal:Meal){return meal.provenance==='user'?'Added by you · unverified':meal.nutritionStatus==='verified'?'Published nutrition':meal.nutritionStatus==='estimated'?(meal.estimationMethod==='ai'?'KI-geschätzt · keine bestätigten Restaurantwerte':'Estimated nutrition'):'Nutrition unknown';}
 async function chooseSelected(){if(!selectedMeal)return;if(await persist(committed,saved,chooseMeal(activity,selectedMeal))){go('History');setMessage('Meal chosen. Mark it as eaten after your meal.');}}
 async function changeHistory(id:string,patch:Partial<Pick<HistoryEntry,'eatenAt'|'rating'|'photoUri'>>){try{return await persist(committed,saved,updateHistory(activity,id,patch));}catch(e){setMessage(e instanceof Error?e.message:'Your history could not be updated.');return false;}}
 async function removeEntry(id:string){const entry=activity.history.find(e=>e.id===id);if(!entry)return false;try{if(await persist(committed,saved,removeHistoryEntry(activity,id))){if(entry.photoUri&&!activity.history.some(e=>e.id!==id&&e.photoUri===entry.photoUri)){try{deletePhotoCopy(entry.photoUri);}catch{setMessage('Entry removed. Its photo copy could not be deleted; you can clear app copies in Privacy & data.');}}return true;}return false;}catch(e){setMessage(e instanceof Error?e.message:'The entry could not be removed.');return false;}}
 function report(meal:Meal|null){setReportMeal(meal);go(meal?'Report':'Support');}
 async function saveReport(text:string){return persist(committed,saved,{...activity,reports:[{id:newId('report'),mealId:reportMeal?.id??null,mealName:reportMeal?.name??null,text,createdAt:new Date().toISOString(),status:'saved-locally'},...activity.reports]});}
 async function addMenu(meal:Meal){if(await persist(committed,saved,{...activity,importedMeals:[...activity.importedMeals,meal]})){setPlace({lat:meal.lat,lon:meal.lon,name:meal.restaurant+' · menu location'});setPreviewId(meal.id);go('Map');setMessage('Your confirmed dish is saved. Active filters still apply.');return true;}return false;}
 async function toggleRestaurant(meal:Meal|null=selectedMeal){if(!meal)return;const key=restaurantKey(meal),next=activity.savedRestaurants.includes(key)?activity.savedRestaurants.filter(id=>id!==key):[...activity.savedRestaurants,key];if(await persist(committed,saved,{...activity,savedRestaurants:next}))setMessage(next.includes(key)?'Restaurant saved on this device.':'Restaurant removed from favourites.');}
 async function exportData(){try{await exportRecords({targets:committed,saved,activity});}catch(e){setMessage(e instanceof Error?e.message:'Your data could not be exported.');}}
 function eraseData(){Alert.alert('Delete your MacroMize data?','This removes your saved preferences, imported menus, history, feedback and this app’s photo copies. Your original photos stay in Photos.',[{text:'Cancel',style:'cancel'},{text:'Delete data',style:'destructive',onPress:()=>{void (async()=>{if(await persist(defaults,[],emptyActivity(),false)){setCalories(String(defaults.calories));setProtein(String(defaults.protein));setExclusions('');setSelectedMeal(null);manualStarted.current=false;setSelectedIntent(null);setGoal('');dirty.current=false;autoLocated.current=false;setScreen('Home');try{deleteOwnedPhotos();setMessage('Your MacroMize data has been deleted from this device.');}catch{setMessage('Records deleted. Photo copies could not be removed; please retry deleting your data.');}}})();}}]);}
 function nutritionSummary(meal:Meal){return meal.nutritionStatus==='unknown'?'Nutrition unavailable':`${meal.calories??'—'} kcal · ${meal.protein??'—'} g protein`;}
 function fields(){return <>
  <View style={s.numberGrid}>
   <View style={s.numberCard}><Text style={s.fieldLabel}>Calories</Text><View style={s.numberRow}><TextInput accessibilityLabel="Calories for this meal" keyboardType="number-pad" value={calories} maxLength={5} onChangeText={v=>{dirty.current=true;setCalories(v);}} style={s.numberInput}/><Text style={s.unit}>kcal</Text></View></View>
   <View style={s.numberCard}><Text style={s.fieldLabel}>Protein (minimum)</Text><View style={s.numberRow}><TextInput accessibilityLabel="Minimum protein in grams" keyboardType="number-pad" value={protein} maxLength={4} onChangeText={v=>{dirty.current=true;setProtein(v);}} style={s.numberInput}/><Text style={s.unit}>g</Text></View></View>
  </View>
  <View style={{flexDirection:'row',gap:12}}>{(['fatMax','carbsMax'] as const).map(key=><View key={key} style={{flex:1}}><Text style={s.label}>{key==='fatMax'?'Fat':'Carbs'} · max g</Text><TextInput accessibilityLabel={key==='fatMax'?'Maximum fat in grams':'Maximum carbohydrates in grams'} keyboardType="decimal-pad" placeholder="No limit" value={targets[key]===null?'':String(targets[key])} onChangeText={v=>edit(key,v.trim()===''?null:Number(v.replace(',','.')))} style={s.input}/></View>)}</View>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:20}}><Text style={s.label}>Vegan</Text><Switch accessibilityLabel="Vegan" value={targets.diet==='Vegan'} onValueChange={v=>edit('diet',v?'Vegan':'Any')} trackColor={{true:C.green}}/></View>
 </>}
 function mealRow(meal:Meal|Match){return <Pressable key={meal.id} accessibilityRole="button" accessibilityLabel={`${meal.name}, ${meal.restaurant}. View meal`} onPress={()=>openMeal(meal)} style={s.mealRow}>
  {meal.imageUrl&&<Image source={{uri:meal.imageUrl}} style={s.mealThumb}/>}
  <View style={{flex:1}}><Text style={s.mealTitle}>{meal.name}</Text><Text style={s.mealSub}>{meal.restaurant}</Text><Text style={s.mealSub}>{nutritionSummary(meal)}</Text><Text style={s.mealMeta}>{[nutritionLabel(meal),...('goalFit' in meal&&meal.goalFit?[`${meal.goalFit} goal fit`]:[]),...('distanceKm' in meal?[`${meal.distanceKm.toFixed(1)} km straight line`]:[]),...(meal.price?[meal.price]:[])].join(' · ')}</Text></View>
  <View style={s.rowEnd}>{'score' in meal&&meal.score!==null&&<View style={s.score}><Text style={s.scoreText}>{meal.score}</Text></View>}<Icon name="chevron-forward" size={17}/></View>
 </Pressable>}
 const showHeader=screen==='Home'||screen==='Profile'||screen==='Saved';
 const showNavigation=onboardingCompleted&&(screen==='Map'||screen==='Saved'||screen==='Profile');
 return <SafeAreaView style={s.root} edges={['top','left','right']}><StatusBar style="dark"/>
  {showHeader&&<View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="MacroMize Home" onPress={()=>go(onboardingCompleted?'Map':'Home')}><Text style={s.wordmark}>MacroMize</Text></Pressable>{onboardingCompleted&&<Pressable accessibilityRole="button" accessibilityLabel="Profile" onPress={()=>go('Profile')} style={s.headerProfile}><Icon name="person-outline" size={23}/></Pressable>}</View>}
  <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}>
  {screen==='Map'?<FindMeals onVegan={vegan=>void persist({...committed,diet:vegan?'Vegan':'Any'})} layout={finderLayout} onLayout={setFinderLayout} targets={committed} matches={matches} place={place} locationAllowed={locationStatus==='Allowed'} locating={locating} locationError={locationError} area={area} onArea={setArea} onSearch={()=>void findArea()} onLocate={()=>void locate()} onMacros={async macros=>persist(validateTargets({...committed,calories:macros.calories,protein:macros.protein,fatMax:macros.fat,carbsMax:macros.carbs,mode:'numeric'}))} onEdit={()=>go('Targets')} selectedId={preview?.id??null} onSelect={meal=>setPreviewId(meal.id)} onOpen={openMeal} saved={saved} restaurants={activity.savedRestaurants} saving={saving||!ready} onSave={meal=>void toggleSaved(meal)} onRestaurant={meal=>void toggleRestaurant(meal)} onLink={url=>void openLink(url)} catalogStatus={catalogStatus} catalogCount={restaurantCatalog.length}/>:<ScrollView ref={scrollRef} contentContainerStyle={[s.content,screen==='Home'&&s.homeContent,screen==='Meal'&&s.detailContent]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
   {screen==='Loading'&&<><Text accessibilityRole="header" style={s.title}>Loading your preferences…</Text>{message?<Button title="Retry loading preferences" onPress={()=>void restore()}/>:<ActivityIndicator color={C.green}/>}</>}
   {screen==='Home'&&<>
    <Text style={[s.hero,compact&&s.heroCompact]}>Find food{'\n'}that fits{'\n'}your goals</Text>
    <Text style={s.subtitle}>Find the right meals near you — based on your goals, not guesswork.</Text>
    <View style={[s.greeting,compact&&s.greetingCompact]}><Image source={mascot} style={[s.mize,compact&&s.mizeCompact]} accessibilityLabel="Mize, your avocado guide"/><View style={s.bubble}><Text style={s.bubbleText}><Text style={{fontWeight:'700'}}>Hey!</Text>{'\n'}What are we looking for today?</Text><View style={s.bubbleTail}/></View></View>
    <Button title="Get started" icon="arrow-forward" onPress={()=>go('SearchMethod')}/><Text style={s.guestNote}>Your next meal. No account needed.</Text>
   </>}
   {screen==='SearchMethod'&&<><Button title="Back" secondary onPress={()=>go('Home')}/><Text accessibilityRole="header" style={s.title}>How would you like to search?</Text><Button title="I know my targets" icon="locate-outline" onPress={startManual}/><Text style={s.body}>Set calories, protein and more.</Text><Button title="Help me choose" icon="leaf-outline" secondary onPress={startHelp}/><Text style={s.body}>Start with a goal and review your macros.</Text></>}
   {screen==='Targets'&&<>
    <Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>go(targetBack)} style={s.back}><Icon name="chevron-back" size={25}/></Pressable><Text accessibilityRole="header" style={s.title}>Set your macros</Text>{fields()}{!ready&&<Button title="Retry loading preferences" secondary onPress={()=>void restore()}/>}
   </>}
   {screen==='Profile'&&<>
    <Text accessibilityRole="header" style={s.title}>Your space</Text><Text style={s.body}>A little less setup next time. No account needed.</Text>
    <View style={s.direction}><Text style={s.directionTitle}>{stats.chosen} chosen · {stats.eaten} eaten</Text><Text style={s.body}>{stats.favourites} favourite meals · {stats.restaurants} restaurants</Text><Text style={s.small}>{stats.photos} meal photos · {stats.rated} ratings</Text></View>
    <Button title="Meal history" icon="time-outline" secondary onPress={()=>go('History')}/><Button title="Goals & preferences" icon="options-outline" secondary onPress={()=>go('Targets')}/><Button title="Add a real menu" icon="document-text-outline" secondary onPress={()=>go('Menu')}/><Button title="Privacy & data" icon="shield-checkmark-outline" secondary onPress={()=>go('Privacy')}/><Button title="Support & feedback" icon="chatbubble-outline" secondary onPress={()=>report(null)}/>
    <View style={s.profileBlock}><View style={s.between}><Text style={s.fieldLabel}>Location access</Text><Text style={s.fieldLabel}>{locationStatus}</Text></View><Button title={locating?'Finding location…':'Use my location'} secondary disabled={locating} icon="navigate-outline" onPress={()=>void locate()}/><Button title="Device permission settings" secondary onPress={()=>void Linking.openSettings().catch(()=>setMessage('Open Settings on your device to manage permissions.'))}/><Text style={s.small}>The launch area is Hamburg Zentrum. Location is requested on your first meal search and refreshed on app return if allowed.</Text></View>{!ready&&<Button title="Retry loading preferences" secondary onPress={()=>void restore()}/>}
   </>}
   {(['History','Menu','Report','Privacy','Support'] as Screen[]).includes(screen)&&<><Pressable accessibilityRole="button" accessibilityLabel="Back to Profile" onPress={()=>go('Profile')} style={s.back}><Icon name="chevron-back" size={25}/></Pressable><Text accessibilityRole="header" style={s.title}>{screen==='History'?'Your meal history':screen==='Menu'?'Add a menu':screen==='Privacy'?'Privacy & data':screen==='Support'?'Support & feedback':'Report a correction'}</Text></>}
   {screen==='History'&&<HistoryScreen activity={activity} saving={saving||!ready} onUpdate={changeHistory} onRemove={removeEntry} onOpen={openMeal} onReport={report}/>}
   {screen==='Menu'&&<MenuCapture place={place} mealType={targets.mealType} saving={saving||!ready} onSave={addMenu}/>}
   {(screen==='Report'||screen==='Support')&&<ReportScreen key={reportMeal?.id??'general'} meal={reportMeal} reports={activity.reports} saving={saving||!ready} onSave={saveReport}/>}
   {screen==='Privacy'&&<><Text style={s.sectionTitle}>Your data stays with you</Text><Text style={s.body}>Goals, favourites, entered menus, feedback and meal history are stored on this device. Photos are copied into this app’s storage. They are not uploaded to MacroMize or synced with the website.</Text><Text style={[s.sectionTitle,{marginTop:24}]}>When you use the map</Text><Text style={s.body}>Area searches send your typed address to OpenStreetMap’s Nominatim service. Map tiles request the visible area from Apple and OpenTopoMap. Directions open Apple Maps with the restaurant location. These services receive your network address. Photo text recognition downloads code and language files from jsDelivr; the photo is processed on this device.</Text><Text style={[s.sectionTitle,{marginTop:24}]}>Permissions</Text><Text style={s.body}>Location is requested on your first meal search and refreshed on app return if allowed. Camera access is requested when you use it. Choose a photo through the system picker; no full photo-library access is required.</Text><Button title="Manage device permissions" secondary onPress={()=>void Linking.openSettings()}/><Text style={[s.sectionTitle,{marginTop:24}]}>Take your data with you</Text><Text style={s.body}>Export your records as a JSON file. Photos can be shared separately from each entry in Meal history.</Text><Button title="Export my records" secondary disabled={!ready} onPress={()=>void exportData()}/><Button title="Delete my data from this device" secondary disabled={saving||!ready} onPress={eraseData}/></>}
   {screen==='Help'&&<>
    <Pressable accessibilityRole="button" accessibilityLabel="Back to search method" onPress={()=>go(onboardingCompleted?'Map':'SearchMethod')} style={s.back}><Icon name="chevron-back" size={25}/></Pressable>
    <View style={s.helpHeading}><View style={{flex:1}}><Text accessibilityRole="header" style={s.title}>What do you{'\n'}need today?</Text></View><Image source={mascot} style={s.mizeSmall}/></View>
    <View style={s.intentGrid}>{intents.map((i,index)=><Pressable key={i.title} accessibilityRole="button" accessibilityState={{selected:selectedIntent===index}} onPress={()=>chooseIntent(index)} style={[s.intent,selectedIntent===index&&s.intentSelected]}><Text style={s.intentText}>{i.title}</Text><Icon name={selectedIntent===index?'checkmark':'arrow-forward'} size={18}/></Pressable>)}</View>
    <Text style={s.label}>Or describe it in your own words</Text><TextInput accessibilityLabel="Describe your goal" multiline value={goal} onChangeText={setGoal} maxLength={500} placeholder="I’ve just finished a workout…" placeholderTextColor={C.muted} style={[s.input,{minHeight:82,textAlignVertical:'top'}]}/><Button title="Find a direction" secondary disabled={!goal.trim()} onPress={helpFromWords}/>
    {selectedIntent!==null&&<View style={s.direction}><Text style={s.eyebrow}>YOUR STARTING POINT</Text><Text style={s.directionTitle}>{intents[selectedIntent].description}</Text><Text style={s.small}>A starting point for your meal macros. Review and adjust the suggested values next.</Text></View>}
    <Button title="Review my macros" icon="arrow-forward" disabled={selectedIntent===null} onPress={()=>go('Targets')}/>
   </>}
   {screen==='Saved'&&<><Text accessibilityRole="header" style={s.title}>Your favourites</Text><View style={s.chips}>{(['Meals','Restaurants'] as const).map(v=><Chip key={v} label={v} selected={savedView===v} onPress={()=>setSavedView(v)}/>)}</View>{savedView==='Meals'?(meals.some(m=>saved.includes(m.id))?meals.filter(m=>saved.includes(m.id)).map(mealRow):<Empty icon="heart-outline" title="Your favourites start here." body="Save a meal you like and come back to it when you’re hungry." action={<Button title="Explore meals" icon="arrow-forward" onPress={()=>go('Map')}/>}/>):activity.savedRestaurants.length?activity.savedRestaurants.map(key=>{const restaurantMeals=meals.filter(m=>restaurantKey(m)===key);return <View key={key} style={s.direction}><Text style={s.directionTitle}>{restaurantMeals[0]?.restaurant??'Saved restaurant'}</Text>{restaurantMeals.map(mealRow)}<Button title="Remove restaurant favourite" secondary disabled={saving||!ready} onPress={()=>void persist(committed,saved,{...activity,savedRestaurants:activity.savedRestaurants.filter(id=>id!==key)})}/></View>;}):<Empty icon="restaurant-outline" title="Places worth coming back to." body="Save a restaurant from a dish’s details."/>}</>}
   {screen==='Meal'&&selectedMeal&&<>
    {selectedMeal.imageUrl?<View><Image source={{uri:selectedMeal.imageUrl}} style={s.dishImage}/><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>go(mealBack)} style={s.imageBack}><Icon name="arrow-back" size={22}/></Pressable></View>:<Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>go(mealBack)} style={[s.back,{marginLeft:20}]}><Icon name="chevron-back" size={25}/></Pressable>}
    {!selectedMeal.imageUrl&&<View style={{marginHorizontal:20}}><DishIllustration meal={selectedMeal} detail/></View>}
    <View style={s.detailBody}><View style={s.between}><View style={{flex:1}}><Text accessibilityRole="header" style={s.dishTitle}>{selectedMeal.name}</Text><Text style={s.body}>{selectedMeal.restaurant}</Text>{/^https?:\/\//i.test(selectedMeal.menuUrl)?<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.menuUrl)}><Text style={s.sourceLink}>Restaurant website ↗</Text></Pressable>:<Text style={s.small}>Website unavailable</Text>}{detailMatch&&<Text style={s.small}>{detailMatch.distanceKm.toFixed(1)} km straight line</Text>}</View><AvocadoScore score={detailMatch?.score??null}/></View>
     <View style={s.macros}>{[[selectedMeal.calories,'kcal'],[selectedMeal.protein,'protein (g)'],[selectedMeal.carbs,'carbs (g)'],[selectedMeal.fat,'fat (g)']].map(([v,label])=><View key={String(label)} style={s.macro}><Text style={s.macroValue}>{selectedMeal.nutritionStatus==='unknown'?'—':v??'—'}</Text><Text style={s.macroLabel}>{label}</Text></View>)}</View>
     <View style={s.direction}><Text style={s.directionTitle}>Why this matches you</Text>{(detailMatch?.reasons??['Set your location and targets to see your match.']).map(reason=><View key={reason} style={s.reasonRow}><Icon name={/unavailable|above|below|estimated|unconfirmed|Set your/.test(reason)?'information-circle-outline':'checkmark'} size={17}/><Text style={s.reason}>{reason}</Text></View>)}<Text style={s.small}>Match Score is a decision aid, not a scientific measurement.</Text></View>
     <>{selectedMeal.imageUrl&&selectedMeal.imageSourceUrl&&<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.imageSourceUrl!)}><Text style={s.sourceLink}>Foto: {selectedMeal.imageAttribution||"Restaurantwebsite"} ↗</Text></Pressable>}</><Text style={s.sectionTitle}>Ingredients</Text><Text style={s.body}>{selectedMeal.ingredients?.join(', ')||(selectedMeal.imageUrl||selectedMeal.sourcePhotoUri||selectedMeal.sourceKind==='photo'?'Ingredients are not confirmed. Any identification from images is an estimate, not a verified ingredient list.':'Ingredient information is unavailable; no image-based estimate is available.')}</Text>
     <Text style={[s.sectionTitle,{marginTop:24}]}>Nutrition</Text><Text style={s.body}>{selectedMeal.provenance==='user'?'Added by you · not independently verified':selectedMeal.nutritionStatus==='verified'?'Published by the restaurant':selectedMeal.nutritionStatus==='estimated'?`Estimated · ${selectedMeal.confidence??'Unknown'} confidence`:'Nutrition information is unknown.'}</Text>
     {selectedMeal.assumptions&&<Text style={s.small}>{selectedMeal.assumptions}</Text>}{selectedMeal.menuUrl?<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.menuUrl)}><Text style={s.sourceLink}>Original restaurant menu ↗</Text></Pressable>:<><Text style={s.sourceLink}>{selectedMeal.sourceKind==='photo'?'Original menu photo':'Original menu text'}</Text>{selectedMeal.sourceKind==='photo'&&selectedMeal.sourceReference&&<Image source={{uri:selectedMeal.sourceReference}} accessibilityLabel="Original menu photo" style={{width:'100%',height:220,resizeMode:'contain'}}/>}{selectedMeal.evidenceText&&<Text style={s.body}>{selectedMeal.evidenceText}</Text>}</>}{selectedMeal.sourcePhotoUri&&selectedMeal.sourceKind!=='photo'&&<Image source={{uri:selectedMeal.sourcePhotoUri}} accessibilityLabel="Original menu photo" style={{width:'100%',height:220,resizeMode:'contain',marginTop:12}}/>}{selectedMeal.nutritionSource&&<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.nutritionSource!)}><Text style={s.sourceLink}>Nutrition source ↗</Text></Pressable>}
     <Text style={s.small}>{openingInfo(selectedMeal).label}</Text>{selectedMeal.openingHours&&<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.openingHours!.sourceUrl)}><Text style={s.sourceLink}>Published opening hours ↗</Text></Pressable>}<Text style={s.small}>Checked {new Date(selectedMeal.checkedAt).toLocaleDateString()}. {selectedMeal.available===null?'Current availability is unknown.':'Confirm current availability with the restaurant.'}</Text>{selectedMeal.price&&<Text style={[s.body,{marginTop:12}]}>{selectedMeal.price}</Text>}<Button title={saved.includes(selectedMeal.id)?'Saved meal':'Save meal'} icon={saved.includes(selectedMeal.id)?'heart':'heart-outline'} secondary disabled={saving||!ready} onPress={()=>void toggleSaved()}/><Button title={activity.savedRestaurants.includes(restaurantKey(selectedMeal))?'Restaurant saved':'Save restaurant'} icon="restaurant-outline" secondary disabled={saving||!ready} onPress={()=>void toggleRestaurant()}/><Button title="Report incorrect information" secondary onPress={()=>report(selectedMeal)}/>
    </View>
   </>}
  </ScrollView>}
  {message!==''&&<Text accessibilityRole="alert" accessibilityLiveRegion="polite" style={s.globalNotice}>{message}</Text>}{screen==='Profile'&&locationError!==''&&<Text accessibilityRole="alert" style={s.globalNotice}>{locationError}</Text>}
  {screen==='Targets'&&<SafeAreaView edges={['bottom']} style={s.actionDock}><Button title={saving?'Saving…':'Find my meals'} icon="arrow-forward" disabled={saving||!ready} onPress={()=>void submitTargets()}/></SafeAreaView>}
  {screen==='Meal'&&selectedMeal&&<SafeAreaView edges={['bottom']} style={s.actionDock}><View style={s.actionRow}><View style={{flex:1.35}}><Button title="Get directions" onPress={()=>void openLink(`https://maps.apple.com/?daddr=${selectedMeal.lat},${selectedMeal.lon}&dirflg=w`)}/></View></View></SafeAreaView>}
  </KeyboardAvoidingView>
  {showNavigation&&<SafeAreaView edges={['bottom']} style={s.navSafe}><View style={s.nav}>{navigation.map(item=><Pressable key={item.name} accessibilityRole="tab" accessibilityState={{selected:screen===item.name}} onPress={()=>go(item.name)} style={s.navItem}><Icon name={screen===item.name?item.active:item.icon} size={23} color={screen===item.name?C.green:'#818792'}/><Text style={[s.navText,screen===item.name&&{color:C.green,fontWeight:'700'}]}>{item.name==='Map'?'Find my meals':item.name==='Saved'?'Favourites':item.name}</Text></Pressable>)}</View></SafeAreaView>}
 </SafeAreaView>;
}
export default function App(){return <SafeAreaProvider><MacroMize/></SafeAreaProvider>;}
const s=StyleSheet.create({
 root:{flex:1,backgroundColor:C.bg},
 header:{height:54,paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},wordmark:{fontSize:23,fontWeight:'700',letterSpacing:-.8,color:C.green},headerProfile:{height:44,width:36,alignItems:'center',justifyContent:'center'},
 content:{paddingHorizontal:22,paddingTop:8,paddingBottom:26,maxWidth:500,width:'100%',alignSelf:'center'},homeContent:{paddingTop:10,paddingBottom:10},
 hero:{fontSize:46,lineHeight:48,fontWeight:'800',letterSpacing:-2.1,color:C.ink,marginTop:8,marginBottom:20},heroCompact:{fontSize:41,lineHeight:43,marginTop:4,marginBottom:15},subtitle:{fontSize:16,lineHeight:24,color:C.muted,maxWidth:350},
 greeting:{flexDirection:'row',alignItems:'center',gap:8,marginTop:18,marginBottom:12,minHeight:171},greetingCompact:{marginTop:10,marginBottom:9,minHeight:141},mize:{width:140,height:169,resizeMode:'contain'},mizeCompact:{width:124,height:141},mizeSmall:{width:87,height:106,resizeMode:'contain'},bubble:{flex:1,backgroundColor:C.white,borderRadius:22,paddingVertical:18,paddingHorizontal:18,marginBottom:32},bubbleText:{fontSize:16,lineHeight:22,color:C.ink},bubbleTail:{position:'absolute',bottom:-14,left:24,width:0,height:0,borderLeftWidth:0,borderRightWidth:21,borderTopWidth:20,borderRightColor:'transparent',borderTopColor:C.white},
 entry:{flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:18,paddingVertical:19,backgroundColor:C.white,borderRadius:16,marginBottom:12,minHeight:88},entryTitle:{fontSize:17,fontWeight:'600',color:C.ink,letterSpacing:-.45,marginBottom:5},entryBody:{fontSize:13,lineHeight:19,color:C.muted},guestNote:{fontSize:11,color:C.muted,textAlign:'center',marginTop:0,marginBottom:0},
 pressed:{opacity:.75},disabled:{opacity:.4},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.6,color:C.muted,marginTop:0,marginBottom:10},title:{fontSize:35,lineHeight:39,fontWeight:'700',color:C.ink,letterSpacing:-1.6,marginBottom:24,marginTop:8},body:{fontSize:15,lineHeight:23,color:C.muted},small:{fontSize:12,lineHeight:18,color:C.muted,marginTop:8},back:{height:48,width:48,alignItems:'flex-start',justifyContent:'center',marginLeft:-5,marginBottom:10},
 button:{minHeight:54,borderRadius:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12,paddingVertical:15,paddingHorizontal:16,marginTop:18,borderWidth:1},primary:{backgroundColor:C.green,borderColor:C.green},secondary:{backgroundColor:'#EEF0E9',borderColor:'#EEF0E9'},buttonText:{fontSize:16,fontWeight:'600',color:C.white},
 numberGrid:{gap:13},numberCard:{paddingHorizontal:22,paddingVertical:16,borderRadius:15,backgroundColor:C.white},fieldLabel:{fontSize:15,fontWeight:'400',color:C.ink},numberRow:{flexDirection:'row',alignItems:'center',gap:12,marginTop:7},numberInput:{flex:1,minWidth:0,fontSize:32,fontWeight:'500',letterSpacing:-1,color:C.ink,padding:0},unit:{fontSize:14,color:C.muted,fontWeight:'400'},label:{fontSize:15,fontWeight:'500',color:C.ink,marginTop:21,marginBottom:12},
 mealTypes:{flexDirection:'row',gap:7},mealType:{flex:1,alignItems:'center',justifyContent:'center',gap:9,paddingVertical:12,backgroundColor:'#F0F1EB',borderWidth:1,borderColor:'transparent',borderRadius:13,minHeight:79},mealTypeSelected:{backgroundColor:C.white,borderColor:C.green},mealTypeText:{fontSize:12,color:C.ink},radiusHeading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:23,marginBottom:3},radius:{fontSize:15,color:C.ink},slider:{width:'100%',height:40},
 chips:{flexDirection:'row',gap:8,flexWrap:'wrap'},chip:{paddingHorizontal:15,paddingVertical:12,borderRadius:11,backgroundColor:C.white,borderWidth:1,borderColor:'transparent'},chipSelected:{backgroundColor:C.green,borderColor:C.green},chipText:{fontSize:13,color:C.ink,fontWeight:'500'},input:{fontSize:15,lineHeight:22,backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:12,padding:14,color:C.ink,minHeight:50},
 profileBlock:{borderTopWidth:1,borderColor:C.line,marginTop:30,paddingTop:24},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},helpHeading:{flexDirection:'row',alignItems:'center'},intentGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:10},intent:{width:'48%',flexGrow:1,minHeight:76,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'space-between',padding:15,borderWidth:1,borderColor:C.line,borderRadius:13,backgroundColor:C.white},intentSelected:{backgroundColor:'#EDF5D7',borderColor:'#6F8D45'},intentText:{fontSize:14,fontWeight:'600',color:C.ink,flex:1,lineHeight:20},
 direction:{backgroundColor:C.soft,padding:19,borderRadius:15,marginTop:22,marginBottom:22},directionTitle:{fontSize:17,fontWeight:'600',lineHeight:24,color:C.ink,marginBottom:10},notice:{fontSize:14,lineHeight:21,backgroundColor:'#EDF1DD',color:'#42572F',padding:15,borderRadius:12,marginTop:16},globalNotice:{fontSize:13,lineHeight:19,backgroundColor:'#EDF1DD',color:'#42572F',paddingVertical:12,paddingHorizontal:20},
 discovery:{flex:1,backgroundColor:C.bg},searchBox:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:C.white,borderRadius:29,paddingLeft:18,paddingRight:6,minHeight:56},searchInput:{flex:1,fontSize:15,minHeight:54,color:C.ink},searchAction:{width:42,height:44,alignItems:'center',justifyContent:'center'},mapTop:{position:'absolute',top:12,left:16,right:16},areaCaption:{alignSelf:'flex-start',maxWidth:'100%',backgroundColor:C.white,fontSize:12,color:C.muted,paddingHorizontal:12,paddingVertical:7,borderRadius:13,marginTop:8},mapError:{fontSize:13,lineHeight:19,color:C.green,backgroundColor:C.white,padding:12,borderRadius:13,marginTop:8},mapBottom:{position:'absolute',left:16,right:16,bottom:6,gap:12},mapAttribution:{alignSelf:'stretch',backgroundColor:'#FFFFFFED',paddingHorizontal:6,paddingVertical:3,borderRadius:4},mapAttributionText:{fontSize:10,lineHeight:13,color:'#46534A',textAlign:'center'},locateButton:{alignSelf:'flex-start',width:52,height:52,borderRadius:26,backgroundColor:C.white,alignItems:'center',justifyContent:'center',marginBottom:1},segment:{backgroundColor:'#F8F9F4',borderRadius:29,padding:7,flexDirection:'row'},segmentItem:{flex:1,alignItems:'center',justifyContent:'center',minHeight:40,paddingVertical:9,borderRadius:22,backgroundColor:'#EFF0EA'},segmentActive:{backgroundColor:C.green},segmentText:{fontSize:15,color:C.ink,fontWeight:'500'},
 mapScore:{backgroundColor:'#EEF4B9',width:54,height:54,borderRadius:27,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:C.white},mapScoreSelected:{backgroundColor:C.green,width:74,height:74,borderRadius:37},mapScoreText:{fontSize:26,color:C.green,fontWeight:'700',letterSpacing:-1},mapScoreLabel:{fontSize:8,color:C.green,letterSpacing:.5},compactState:{backgroundColor:C.white,borderRadius:18,padding:18},compactStateHeading:{flexDirection:'row',gap:10,alignItems:'center'},compactStateTitle:{fontSize:17,fontWeight:'600',lineHeight:22,color:C.ink,flexShrink:1},compactStateBody:{fontSize:13,lineHeight:20,color:C.muted,marginTop:7},inlineAction:{fontSize:14,fontWeight:'600',color:C.green,paddingTop:12},closestNotice:{fontSize:12,lineHeight:18,padding:12,backgroundColor:C.white,borderRadius:12,color:C.green},
 preview:{flexDirection:'row',gap:12,backgroundColor:C.white,borderRadius:18,padding:12,alignItems:'center'},previewImage:{width:77,height:98,borderRadius:11},previewNumbers:{fontSize:13,lineHeight:18,color:C.ink,marginTop:10,paddingTop:9,borderTopWidth:1,borderColor:C.line},listTop:{paddingHorizontal:16,paddingTop:12,gap:14},listContent:{paddingHorizontal:20,paddingTop:25,paddingBottom:24},listTitle:{fontSize:23,lineHeight:28,fontWeight:'700',letterSpacing:-.9,color:C.ink,marginBottom:18},
 sectionTitle:{fontSize:17,fontWeight:'600',color:C.ink,marginBottom:7},empty:{backgroundColor:C.white,borderRadius:18,padding:24,marginTop:8},emptyTitle:{fontSize:24,lineHeight:28,fontWeight:'600',letterSpacing:-.7,color:C.ink,marginTop:18,marginBottom:12},navSafe:{backgroundColor:C.bg,borderTopWidth:1,borderTopColor:'#E8EBE2'},nav:{flexDirection:'row',justifyContent:'space-around',paddingTop:10,paddingBottom:7},navItem:{alignItems:'center',gap:5,minWidth:66,paddingVertical:3},navText:{fontSize:11,color:'#818792'},
 mealRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:18,borderBottomWidth:1,borderColor:C.line},mealThumb:{width:76,height:92,borderRadius:12},mealTitle:{fontSize:15,fontWeight:'600',lineHeight:20,color:C.ink,letterSpacing:-.3},mealSub:{fontSize:13,lineHeight:19,color:C.muted,marginTop:3},mealMeta:{fontSize:11,lineHeight:16,color:C.muted,marginTop:5},rowEnd:{alignItems:'center',gap:12},score:{height:44,width:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:'#EEF4B9'},scoreText:{fontSize:20,fontWeight:'700',color:C.ink},
 detailContent:{paddingHorizontal:0,paddingTop:0,maxWidth:600},detailBody:{paddingHorizontal:20,paddingTop:18},dishImage:{width:'100%',height:300,resizeMode:'cover'},imageBack:{position:'absolute',top:16,left:16,width:44,height:44,borderRadius:22,backgroundColor:C.white,alignItems:'center',justifyContent:'center'},dishTitle:{fontSize:26,lineHeight:30,fontWeight:'600',letterSpacing:-1,color:C.ink,marginBottom:4},detailScore:{width:75,height:75,borderRadius:38,backgroundColor:'#EEF4B9',alignItems:'center',justifyContent:'center'},detailScoreLabel:{fontSize:10,color:C.ink,marginTop:1},macros:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderColor:C.line,marginTop:18,paddingTop:18},macro:{alignItems:'center',flex:1},macroValue:{fontSize:23,fontWeight:'600',letterSpacing:-.8,color:C.ink},macroLabel:{fontSize:12,lineHeight:19,color:C.muted,marginTop:5},reasonRow:{flexDirection:'row',alignItems:'flex-start',gap:8,marginBottom:6},reason:{flex:1,fontSize:14,lineHeight:21,color:C.ink},sourceLink:{fontSize:14,color:C.green,textDecorationLine:'underline',marginTop:15,marginBottom:7},actionRow:{flexDirection:'row',gap:12},actionDock:{paddingHorizontal:20,paddingTop:0,paddingBottom:12,backgroundColor:C.bg}
});
