import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, BackHandler, Image, Keyboard, KeyboardAvoidingView, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as ExpoLocation from 'expo-location';
import MapView, { Marker, UrlTile } from 'react-native-maps';
import Slider from '@react-native-community/slider';
import { defaults, intents, openingInfo, rankMeals, validateTargets, type Targets, type Meal, type Match } from './src/domain';
import { loadPreferences, savePreferences } from './src/storage';
import { catalog, curatedCatalog } from './src/catalog';
import { loadMobileCatalog } from './src/catalog-client';
import { activityStats, chooseMeal, emptyActivity, newId, restaurantKey, removeHistoryEntry, updateHistory, type Activity, type HistoryEntry } from './src/activity';
import { AdvancedTargets, HistoryScreen, MenuCapture, ReportScreen } from './src/FeatureScreens';
import { deleteOwnedPhotos, deletePhotoCopy, exportRecords } from './src/photos';

type Screen = 'Home' | 'Targets' | 'Help' | 'Map' | 'Saved' | 'Profile' | 'Meal' | 'History' | 'Menu' | 'Report' | 'Privacy' | 'Support';
type Place = { lat: number; lon: number; name: string };
type IconName = React.ComponentProps<typeof Ionicons>['name'];
const C = { bg: '#F7F8F3', green: '#073D2B', ink: '#101C21', muted: '#6C786A', lime: '#D1EE75', line: '#E0E7D9', soft: '#EDF2E6', white: '#FFFFFF' };
const mascot = require('./assets/mize.png');
const navigation: { name: Screen; icon: IconName; active: IconName }[] = [
  {name:'Home', icon:'home-outline', active:'home'}, {name:'Map',icon:'map-outline',active:'map'}, {name:'Saved',icon:'heart-outline',active:'heart'}, {name:'Profile',icon:'person-outline',active:'person'}
];
function Icon({name,size=22,color=C.green}:{name:IconName;size?:number;color?:string}) { return <Ionicons name={name} size={size} color={color}/>; }
function Button({title,onPress,secondary=false,disabled=false,icon}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:IconName}) { return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary?s.secondary:s.primary,disabled&&s.disabled,pressed&&s.pressed]}><Text style={[s.buttonText,secondary&&{color:C.green}]}>{title}</Text>{icon&&<Icon name={icon} size={19} color={secondary?C.green:C.white}/>}</Pressable>; }
function Chip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}) { return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[s.chip,selected&&s.chipSelected]}><Text style={[s.chipText,selected&&{color:C.white}]}>{label}</Text></Pressable>; }
function Empty({icon,title,body,action}:{icon:IconName;title:string;body:string;action?:React.ReactNode}) { return <View style={s.empty}><Icon name={icon} size={32}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.body}>{body}</Text>{action}</View>; }

function MacroMize() {
 const {height:windowHeight,width:windowWidth}=useWindowDimensions();
 const compact=windowHeight<860||windowWidth<375;
 const [screen,setScreen]=useState<Screen>('Home');
 const [targets,setTargets]=useState<Targets>(defaults);
 const [calories,setCalories]=useState(String(defaults.calories));
 const [protein,setProtein]=useState(String(defaults.protein));
 const [exclusions,setExclusions]=useState('');
 const [saved,setSaved]=useState<string[]>([]);
 const [activity,setActivity]=useState<Activity>(emptyActivity);
 const [savedView,setSavedView]=useState<'Meals'|'Restaurants'>('Meals');
 const [reportMeal,setReportMeal]=useState<Meal|null>(null);
 const [restaurantCatalog,setRestaurantCatalog]=useState<Meal[]>(catalog);
 const [catalogStatus,setCatalogStatus]=useState('snapshot');
 useEffect(()=>{const controller=new AbortController();void loadMobileCatalog(process.env.EXPO_PUBLIC_CATALOG_API_URL,catalog,curatedCatalog,controller.signal).then(result=>{if(!controller.signal.aborted){setRestaurantCatalog(result.meals);setCatalogStatus(result.status);}});return()=>controller.abort();},[]);
 const meals=[...restaurantCatalog,...activity.importedMeals];
 const hasMeals=meals.length>0;
 const stats=activityStats(activity,saved);
 const [ready,setReady]=useState(false);
 const [saving,setSaving]=useState(false);
 const [message,setMessage]=useState('');
 const [selectedIntent,setSelectedIntent]=useState<number|null>(null);
 const [goal,setGoal]=useState('');
 const [mapMode,setMapMode]=useState<'Map'|'List'>('Map');
 const [place,setPlace]=useState<Place|null>({lat:53.5503,lon:9.9920,name:'Hamburg Zentrum · launch area'});
 const [area,setArea]=useState('');
 const [locating,setLocating]=useState(false);
 const [locationStatus,setLocationStatus]=useState('Not requested');
 const [locationError,setLocationError]=useState('');
 const [previewId,setPreviewId]=useState<string|null>(null);
 const [selectedMeal,setSelectedMeal]=useState<Meal|null>(null);

 const scrollRef=useRef<ScrollView|null>(null);
 const dirty=useRef(false);
 const searchAbort=useRef<AbortController|null>(null);
 const lastSearch=useRef(0);
 const savingRef=useRef(false);
 useEffect(()=>{void restore();return()=>searchAbort.current?.abort();},[]);
 useEffect(()=>{scrollRef.current?.scrollTo({y:0,animated:false});const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(screen==='Home')return false;go(screen==='Meal'?'Map':'Home');return true;});return()=>sub.remove();},[screen]);

 async function restore(){try{const state=await loadPreferences();if(!dirty.current){setTargets(state.targets);setCalories(String(state.targets.calories));setProtein(String(state.targets.protein));setExclusions(state.targets.exclusions.join(', '));}setSaved(state.saved);setActivity(state.activity);setReady(true);setMessage('');}catch(e){setReady(false);setMessage('Your saved preferences couldn’t be loaded. Retry in Profile; existing data will be kept.');}}
 function go(next:Screen){Keyboard.dismiss();setMessage('');setScreen(next);}
 function edit<K extends keyof Targets>(key:K,value:Targets[K]){dirty.current=true;setTargets(t=>({...t,[key]:value}));}
 function formTargets(){return validateTargets({...targets,calories:calories.trim()?Number(calories):NaN,protein:protein.trim()?Number(protein):NaN,exclusions:[...new Set(exclusions.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean))]});}
 async function persist(next:Targets,nextSaved=saved,nextActivity=activity){if(!ready){setMessage('Please retry loading preferences in Profile before saving.');return false;}if(savingRef.current)return false;savingRef.current=true;setSaving(true);try{await savePreferences({targets:next,saved:nextSaved,activity:nextActivity});setTargets(next);setSaved(nextSaved);setActivity(nextActivity);return true;}catch{setMessage('We couldn’t save your changes. Your inputs are still here. Please try again.');return false;}finally{savingRef.current=false;setSaving(false);}}
 async function submitTargets(profile=false){try{const next=formTargets();Keyboard.dismiss();if(await persist(next)){setMessage(profile?'Your preferences are saved on this device.':'');if(!profile){setMapMode('Map');setScreen('Map');}}}catch(e){setMessage(e instanceof Error?e.message:'Please check your targets.');}}
 function chooseIntent(index:number){dirty.current=true;setSelectedIntent(index);const i=intents[index];setTargets(t=>({...t,mode:'goal',goal:i.title,calories:i.calories,protein:i.protein}));setCalories(String(i.calories));setProtein(String(i.protein));setMessage('');}
 function helpFromWords(){const value=goal.toLowerCase();const i=/workout|training|sport/.test(value)?0:/protein|eiwei/.test(value)?1:/light|leicht|weniger/.test(value)?2:/full|satt/.test(value)?3:/muscle|muskel/.test(value)?4:/dinner|abend/.test(value)?5:-1;if(i<0){setMessage('Choose the direction that best describes your goal below. All targets can be adjusted.');return;}chooseIntent(i);Keyboard.dismiss();setMessage('Suggested direction selected. Review your targets next.');}
 async function locate(){if(locating)return;setLocating(true);setLocationError('');try{const permission=await ExpoLocation.requestForegroundPermissionsAsync();setLocationStatus(permission.status==='granted'?'Allowed':permission.canAskAgain?'Not allowed':'Disabled in Settings');if(permission.status!=='granted'){setLocationError('Location is off. You can enter an area instead.');return;}const p=await ExpoLocation.getCurrentPositionAsync({accuracy:ExpoLocation.Accuracy.Balanced});setPlace({lat:p.coords.latitude,lon:p.coords.longitude,name:'Your current location'});}catch{setLocationError('We couldn’t find your location. Please enter an area instead.');}finally{setLocating(false);}}
 async function findArea(){if(!area.trim()||locating||Date.now()-lastSearch.current<1200)return;lastSearch.current=Date.now();searchAbort.current?.abort();const controller=new AbortController();searchAbort.current=controller;const timer=setTimeout(()=>controller.abort(),12000);setLocating(true);setLocationError('');Keyboard.dismiss();try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(area.trim())}`,{headers:{'Accept':'application/json','User-Agent':'MacroMize/1.0 (local Expo preview)'},signal:controller.signal});if(!response.ok)throw new Error();const data=await response.json() as {lat:string;lon:string;display_name:string}[];if(!Array.isArray(data)||!data.length){setLocationError('No area found. Try a city or a more specific address.');return;}const lat=Number(data[0].lat),lon=Number(data[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Error();setPlace({lat,lon,name:data[0].display_name});}catch{setLocationError('Area search is unavailable. Try again or use your location.');}finally{clearTimeout(timer);setLocating(false);}}
 let allMatches:Match[]=[];try{allMatches=place?rankMeals(meals,targets,place):[];}catch{/* A partially entered filter is validated when the user submits. */}
 const matches=allMatches.slice(0,3);
 const mapPins=matches.filter((meal,index,all)=>all.findIndex(other=>restaurantKey(other)===restaurantKey(meal))===index);
 const preview=matches.find(meal=>meal.id===previewId)??matches[0];
 const detailMatch=selectedMeal?allMatches.find(m=>m.id===selectedMeal.id):undefined;
 function openMeal(meal:Meal){setSelectedMeal(meal);go('Meal');}
 async function toggleSaved(){if(!selectedMeal)return;const next=saved.includes(selectedMeal.id)?saved.filter(id=>id!==selectedMeal.id):[...saved,selectedMeal.id];if(await persist(targets,next))setMessage(next.includes(selectedMeal.id)?'Saved on this device.':'Removed from Saved.');}
 async function openLink(url:string){try{await Linking.openURL(url);}catch{Alert.alert('Couldn’t open the link','Please try again.');}}
 function nutritionLabel(meal:Meal){return meal.provenance==='user'?'Added by you · unverified':meal.nutritionStatus==='verified'?'Published nutrition':meal.nutritionStatus==='estimated'?'Estimated nutrition':'Nutrition unknown';}
 async function chooseSelected(){if(!selectedMeal)return;if(await persist(targets,saved,chooseMeal(activity,selectedMeal))){go('History');setMessage('Meal chosen. Mark it as eaten after your meal.');}}
 async function changeHistory(id:string,patch:Partial<Pick<HistoryEntry,'eatenAt'|'rating'|'photoUri'>>){try{return await persist(targets,saved,updateHistory(activity,id,patch));}catch(e){setMessage(e instanceof Error?e.message:'Your history could not be updated.');return false;}}
 async function removeEntry(id:string){const entry=activity.history.find(e=>e.id===id);if(!entry)return false;try{if(await persist(targets,saved,removeHistoryEntry(activity,id))){if(entry.photoUri&&!activity.history.some(e=>e.id!==id&&e.photoUri===entry.photoUri)){try{deletePhotoCopy(entry.photoUri);}catch{setMessage('Entry removed. Its photo copy could not be deleted; you can clear app copies in Privacy & data.');}}return true;}return false;}catch(e){setMessage(e instanceof Error?e.message:'The entry could not be removed.');return false;}}
 function report(meal:Meal|null){setReportMeal(meal);go(meal?'Report':'Support');}
 async function saveReport(text:string){return persist(targets,saved,{...activity,reports:[{id:newId('report'),mealId:reportMeal?.id??null,mealName:reportMeal?.name??null,text,createdAt:new Date().toISOString(),status:'saved-locally'},...activity.reports]});}
 async function addMenu(meal:Meal){if(await persist(targets,saved,{...activity,importedMeals:[...activity.importedMeals,meal]})){setPlace({lat:meal.lat,lon:meal.lon,name:meal.restaurant+' · menu location'});setPreviewId(meal.id);setMapMode('List');go('Map');setMessage('Your confirmed dish is saved. Active filters still apply.');return true;}return false;}
 async function toggleRestaurant(){if(!selectedMeal)return;const key=restaurantKey(selectedMeal),next=activity.savedRestaurants.includes(key)?activity.savedRestaurants.filter(id=>id!==key):[...activity.savedRestaurants,key];if(await persist(targets,saved,{...activity,savedRestaurants:next}))setMessage(next.includes(key)?'Restaurant saved on this device.':'Restaurant removed from favourites.');}
 async function exportData(){try{await exportRecords({targets,saved,activity});}catch(e){setMessage(e instanceof Error?e.message:'Your data could not be exported.');}}
 function eraseData(){Alert.alert('Delete your MacroMize data?','This removes your saved preferences, imported menus, history, feedback and this app’s photo copies. Your original photos stay in Photos.',[{text:'Cancel',style:'cancel'},{text:'Delete data',style:'destructive',onPress:()=>{void (async()=>{if(await persist(defaults,[],emptyActivity())){setCalories(String(defaults.calories));setProtein(String(defaults.protein));setExclusions('');setSelectedMeal(null);try{deleteOwnedPhotos();setMessage('Your MacroMize data has been deleted from this device.');}catch{setMessage('Records deleted. Photo copies could not be removed; please retry deleting your data.');}}})();}}]);}
 function nutritionSummary(meal:Meal){return meal.nutritionStatus==='unknown'?'Nutrition unavailable':`${meal.calories??'—'} kcal · ${meal.protein??'—'} g protein`;}
 function fields(){return <>
  {targets.mode==='goal'?<View style={s.direction}><Text style={s.eyebrow}>YOUR GOAL</Text><Text style={s.directionTitle}>{targets.goal}</Text><Text style={s.body}>We compare actual menu information with this direction. No calorie target is required.</Text><Button title="Change goal" secondary onPress={()=>go('Help')}/><Button title="Use my own macro targets" secondary onPress={()=>edit('mode','numeric')}/></View>:<View style={s.numberGrid}>
   <View style={s.numberCard}><Text style={s.fieldLabel}>Calories</Text><View style={s.numberRow}><TextInput accessibilityLabel="Calories for this meal" keyboardType="number-pad" value={calories} maxLength={5} onChangeText={v=>{dirty.current=true;setCalories(v);}} style={s.numberInput}/><Text style={s.unit}>kcal</Text></View></View>
   <View style={s.numberCard}><Text style={s.fieldLabel}>Protein (minimum)</Text><View style={s.numberRow}><TextInput accessibilityLabel="Minimum protein in grams" keyboardType="number-pad" value={protein} maxLength={4} onChangeText={v=>{dirty.current=true;setProtein(v);}} style={s.numberInput}/><Text style={s.unit}>g</Text></View></View>
  </View>}
  <Text style={s.label}>Meal type</Text><View style={s.mealTypes}>{([{name:'Breakfast',icon:'coffee-outline'},{name:'Lunch',icon:'silverware-fork-knife'},{name:'Dinner',icon:'pot-steam-outline'},{name:'Snack',icon:'food-apple-outline'}] as const).map(item=><Pressable key={item.name} accessibilityRole="radio" accessibilityLabel={item.name} accessibilityState={{checked:targets.mealType===item.name}} onPress={()=>edit('mealType',item.name)} style={[s.mealType,targets.mealType===item.name&&s.mealTypeSelected]}><MaterialCommunityIcons name={item.icon} size={23} color={targets.mealType===item.name?C.green:C.ink} accessible={false}/><Text style={s.mealTypeText}>{item.name}</Text></Pressable>)}</View>
  <View style={s.radiusHeading}><Text style={s.fieldLabel}>Search radius</Text><Text style={s.radius}>{targets.radius} km</Text></View>
  <Slider accessibilityLabel="Search radius in kilometres" accessibilityValue={{min:.5,max:20,now:targets.radius,text:`${targets.radius} kilometres`}} style={s.slider} minimumValue={.5} maximumValue={20} step={.5} value={targets.radius} minimumTrackTintColor={C.green} maximumTrackTintColor={C.line} thumbTintColor={C.green} onValueChange={v=>edit('radius',Math.round(v*2)/2)}/>
  <Text style={s.label}>Dietary requirement</Text><View style={s.chips}>{(['Any','Vegetarian','Vegan'] as const).map(t=><Chip key={t} label={t} selected={targets.diet===t} onPress={()=>edit('diet',t)}/>)}</View>
  <Text style={s.label}>Ingredients to exclude</Text><TextInput accessibilityLabel="Ingredients to exclude" value={exclusions} onChangeText={v=>{dirty.current=true;setExclusions(v);}} maxLength={1000} placeholder="e.g. peanuts, milk" placeholderTextColor={C.muted} style={s.input}/><Text style={s.small}>Separate with commas. Meals with unconfirmed ingredient information won’t be recommended for these exclusions.</Text>
 <AdvancedTargets targets={targets} onChange={edit}/>
 </>}
 function resultContent(){if(!hasMeals)return <Empty icon="restaurant-outline" title="Real menus are the next ingredient." body="Restaurant data isn’t connected yet. Add a real menu to start matching your confirmed dishes." action={<Button title="Add a menu" secondary onPress={()=>go('Menu')}/>}/>;if(!place)return <Empty icon="location-outline" title="Where are we eating?" body="Enter an area or use your location to find nearby meals."/>;if(!matches.length)return <Empty icon="leaf-outline" title="No suitable meals nearby." body="Try a larger search radius. Your dietary requirements and exclusions stay in place." action={<Button title="Adjust search" secondary onPress={()=>go('Targets')}/>}/>;return <>{targets.mode==='numeric'&&!matches.some(m=>m.exact)&&<Text style={s.notice}>No exact match nearby. Here are the closest options.</Text>}{matches.map(meal=>mealRow(meal))}</>}
 function mealRow(meal:Meal|Match){return <Pressable key={meal.id} accessibilityRole="button" accessibilityLabel={`${meal.name}, ${meal.restaurant}. View meal`} onPress={()=>openMeal(meal)} style={s.mealRow}>
  {meal.imageUrl&&<Image source={{uri:meal.imageUrl}} style={s.mealThumb}/>}
  <View style={{flex:1}}><Text style={s.mealTitle}>{meal.name}</Text><Text style={s.mealSub}>{meal.restaurant}</Text><Text style={s.mealSub}>{nutritionSummary(meal)}</Text><Text style={s.mealMeta}>{[nutritionLabel(meal),...('goalFit' in meal&&meal.goalFit?[`${meal.goalFit} goal fit`]:[]),...('distanceKm' in meal?[`${meal.distanceKm.toFixed(1)} km straight line`]:[]),...(meal.price?[meal.price]:[])].join(' · ')}</Text></View>
  <View style={s.rowEnd}>{'score' in meal&&meal.score!==null&&<View style={s.score}><Text style={s.scoreText}>{meal.score}</Text></View>}<Icon name="chevron-forward" size={17}/></View>
 </Pressable>}
 function searchControls(){return <View style={s.searchBox}><Icon name="search-outline" size={20}/><TextInput accessibilityLabel="Search area" value={area} onChangeText={setArea} onSubmitEditing={()=>void findArea()} returnKeyType="search" placeholder="Search this area" placeholderTextColor={C.ink} maxLength={250} style={s.searchInput}/><Pressable accessibilityRole="button" accessibilityLabel="Search this area" accessibilityState={{disabled:locating||!area.trim()}} onPress={()=>void findArea()} disabled={locating||!area.trim()} style={s.searchAction}>{locating?<ActivityIndicator color={C.green}/>:<Icon name="arrow-forward" size={19}/>}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="Edit search targets" onPress={()=>go('Targets')} style={s.searchAction}><Icon name="options-outline" size={22}/></Pressable></View>}
 function mapToggle(){return <View style={s.segment}>{(['Map','List'] as const).map(mode=><Pressable key={mode} accessibilityRole="tab" accessibilityState={{selected:mapMode===mode}} onPress={()=>setMapMode(mode)} style={[s.segmentItem,mapMode===mode&&s.segmentActive]}><Text style={[s.segmentText,mapMode===mode&&{color:C.white}]}>{mode}</Text></Pressable>)}</View>}
 function mapPreview(){
  if(!hasMeals)return <View style={s.compactState}><View style={s.compactStateHeading}><Icon name="restaurant-outline" size={23}/><Text style={s.compactStateTitle}>Real menus are the next ingredient.</Text></View><Text style={s.compactStateBody}>Add a real menu to start matching your confirmed dishes.</Text><Pressable accessibilityRole="button" onPress={()=>go('Menu')}><Text style={s.inlineAction}>Add a menu →</Text></Pressable></View>;
  if(!place)return <View style={s.compactState}><Text style={s.compactStateTitle}>Where are we eating?</Text><Text style={s.compactStateBody}>Search an area or tap the location button to find meals near you.</Text></View>;
  if(!preview)return <View style={s.compactState}><Text style={s.compactStateTitle}>No suitable meals nearby.</Text><Text style={s.compactStateBody}>Try a larger radius. Your dietary requirements stay in place.</Text><Pressable accessibilityRole="button" onPress={()=>go('Targets')}><Text style={s.inlineAction}>Adjust search →</Text></Pressable></View>;
  return <Pressable accessibilityRole="button" accessibilityLabel={`View ${preview.name} at ${preview.restaurant}`} onPress={()=>openMeal(preview)} style={s.preview}>
   {preview.imageUrl&&<Image source={{uri:preview.imageUrl}} style={s.previewImage}/>}
   <View style={{flex:1}}><View style={s.between}><View style={{flex:1}}><Text style={s.mealTitle} numberOfLines={2}>{preview.name}</Text><Text style={s.mealSub} numberOfLines={1}>{preview.restaurant}</Text></View>{preview.score!==null&&<View style={s.score}><Text style={s.scoreText}>{preview.score}</Text></View>}</View><Text style={s.previewNumbers}>{nutritionSummary(preview)}</Text><Text style={s.mealMeta}>{preview.goalFit?`${preview.goalFit} goal fit · `:''}{preview.distanceKm.toFixed(1)} km straight line · {nutritionLabel(preview)}</Text></View>
  </Pressable>;
 }
 function discovery(){return <View style={s.discovery}>
  {mapMode==='Map'?<>
   <MapView key={`${place?.lat??53.5503}:${place?.lon??9.9920}:${targets.radius}`} style={StyleSheet.absoluteFill} initialRegion={{latitude:place?.lat??53.5503,longitude:place?.lon??9.9920,latitudeDelta:Math.max(.012,targets.radius*.025),longitudeDelta:Math.max(.012,targets.radius*.025)}} mapType={Platform.OS==='ios'?'mutedStandard':'none'} userInterfaceStyle="light" showsBuildings={false} showsTraffic={false} pitchEnabled={false} minZoomLevel={3} maxZoomLevel={19} showsUserLocation={locationStatus==='Allowed'} showsMyLocationButton={false} showsPointsOfInterests={false} toolbarEnabled={false} accessibilityLabel="Nearby meal terrain map" mapPadding={{top:80,right:30,bottom:230,left:30}}>
    <UrlTile urlTemplate="https://a.tile.opentopomap.org/{z}/{x}/{y}.png" maximumNativeZ={17} maximumZ={19} minimumZ={0} tileSize={256} opacity={.58} shouldReplaceMapContent/>
    {mapPins.map(meal=><Marker key={meal.id} coordinate={{latitude:meal.lat,longitude:meal.lon}} accessibilityLabel={`${meal.restaurant}, ${matches.filter(m=>restaurantKey(m)===restaurantKey(meal)).length} recommended dishes, ${meal.score??meal.goalFit??'unassessed'} best match`} onPress={()=>setPreviewId(meal.id)}><View style={[s.mapScore,preview&&restaurantKey(preview)===restaurantKey(meal)&&s.mapScoreSelected]}><Text style={[s.mapScoreText,preview&&restaurantKey(preview)===restaurantKey(meal)&&{color:C.lime}]}>{meal.score??'•'}</Text><Text style={[s.mapScoreLabel,preview&&restaurantKey(preview)===restaurantKey(meal)&&{color:C.white}]}>{matches.filter(m=>restaurantKey(m)===restaurantKey(meal)).length} DISHES</Text></View></Marker>)}
   </MapView>
   <View style={s.mapTop}>{searchControls()}{locationError!==''?<Text accessibilityRole="alert" style={s.mapError}>{locationError}</Text>:<Text style={s.areaCaption} numberOfLines={1}>{place?.name??'Choose an area or use your location'}</Text>}</View>
   <View style={s.mapBottom} pointerEvents="box-none"><Pressable accessibilityRole="button" accessibilityLabel="Use my location" accessibilityState={{disabled:locating}} onPress={()=>void locate()} disabled={locating} style={s.locateButton}>{locating?<ActivityIndicator color={C.green}/>:<Icon name="location-outline" size={23}/>}</Pressable>{hasMeals&&targets.mode==='numeric'&&matches.length>0&&!matches.some(m=>m.exact)&&<Text style={s.closestNotice}>No exact match nearby. Here are the closest options.</Text>}{mapToggle()}{mapPreview()}{preview&&matches.filter(m=>restaurantKey(m)===restaurantKey(preview)).length>1&&<Pressable accessibilityRole="button" accessibilityLabel="Show next recommended dish at this restaurant" onPress={()=>{const same=matches.filter(m=>restaurantKey(m)===restaurantKey(preview));setPreviewId(same[(same.findIndex(m=>m.id===preview.id)+1)%same.length].id);}} style={{backgroundColor:C.white,borderRadius:12,padding:8,alignItems:'center'}}><Text style={{fontSize:12,color:C.green}}>Next dish at this restaurant →</Text></Pressable>}<Pressable accessibilityRole="link" accessibilityLabel="Map attribution: OpenStreetMap, SRTM, OpenTopoMap, CC BY SA" onPress={()=>void Linking.openURL('https://opentopomap.org/about')} style={s.mapAttribution}><Text style={s.mapAttributionText}>Map data © OpenStreetMap, SRTM · Map style © OpenTopoMap (CC-BY-SA)</Text></Pressable></View>
  </>:<>
   <View style={s.listTop}>{searchControls()}{mapToggle()}{locationError!==''&&<Text accessibilityRole="alert" style={s.mapError}>{locationError}</Text>}</View>
   <ScrollView contentContainerStyle={s.listContent} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"><Text accessibilityRole="header" style={s.listTitle}>Your top 3 nearby</Text><Text style={[s.small,{marginBottom:12}]}>Hamburg Zentrum pilot · {restaurantCatalog.length} entries at {new Set(restaurantCatalog.map(restaurantKey)).size} restaurants. {catalogStatus==='connected'?'Updated catalog · availability is not live.':catalogStatus==='stale'?'Live refresh unavailable; showing saved menus.':'Saved menu snapshot; availability is not live.'}</Text>{resultContent()}</ScrollView>
  </>}
 </View>}
 const showHeader=screen==='Home'||screen==='Profile'||screen==='Saved';
 const showNavigation=screen==='Home'||screen==='Map'||screen==='Saved'||screen==='Profile';
 return <SafeAreaView style={s.root} edges={['top','left','right']}><StatusBar style="dark"/>
  {showHeader&&<View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="MacroMize Home" onPress={()=>go('Home')}><Text style={s.wordmark}>MacroMize</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Profile" onPress={()=>go('Profile')} style={s.headerProfile}><Icon name="person-outline" size={23}/></Pressable></View>}
  <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}>
  {screen==='Map'?discovery():<ScrollView ref={scrollRef} contentContainerStyle={[s.content,screen==='Home'&&s.homeContent,screen==='Meal'&&s.detailContent]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
   {screen==='Home'&&<>
    <Text style={[s.hero,compact&&s.heroCompact]}>Find food{'\n'}that fits{'\n'}your goals</Text>
    <Text style={s.subtitle}>Find the right meals near you — based on your goals, not guesswork.</Text>
    <View style={[s.greeting,compact&&s.greetingCompact]}><Image source={mascot} style={[s.mize,compact&&s.mizeCompact]} accessibilityLabel="Mize, your avocado guide"/><View style={s.bubble}><Text style={s.bubbleText}><Text style={{fontWeight:'700'}}>Hey!</Text>{'\n'}What are we looking for today?</Text><View style={s.bubbleTail}/></View></View>
    <Pressable accessibilityRole="button" onPress={()=>{edit('mode','numeric');go('Targets');}} style={({pressed})=>[s.entry,pressed&&s.pressed]}><Icon name="locate-outline" size={31}/><View style={{flex:1}}><Text style={s.entryTitle}>I know my targets</Text><Text style={s.entryBody}>Set calories, protein and more.</Text></View><Icon name="chevron-forward" size={21}/></Pressable>
    <Pressable accessibilityRole="button" onPress={()=>go('Help')} style={({pressed})=>[s.entry,pressed&&s.pressed]}><Icon name="leaf-outline" size={31}/><View style={{flex:1}}><Text style={s.entryTitle}>Help me choose</Text><Text style={s.entryBody}>Tell us your goal, we’ll find the right meals.</Text></View><Icon name="chevron-forward" size={21}/></Pressable>
    <Text style={s.guestNote}>Your next meal. No account needed.</Text>
   </>}
   {screen==='Targets'&&<>
    <Pressable accessibilityRole="button" accessibilityLabel="Back to Home" onPress={()=>go('Home')} style={s.back}><Icon name="chevron-back" size={25}/></Pressable><Text accessibilityRole="header" style={s.title}>Your targets</Text>{fields()}{!ready&&<Button title="Retry loading preferences" secondary onPress={()=>void restore()}/>}
   </>}
   {screen==='Profile'&&<>
    <Text accessibilityRole="header" style={s.title}>Your space</Text><Text style={s.body}>A little less setup next time. No account needed.</Text>
    <View style={s.direction}><Text style={s.directionTitle}>{stats.chosen} chosen · {stats.eaten} eaten</Text><Text style={s.body}>{stats.favourites} favourite meals · {stats.restaurants} restaurants</Text><Text style={s.small}>{stats.photos} meal photos · {stats.rated} ratings</Text></View>
    <Button title="Meal history" icon="time-outline" secondary onPress={()=>go('History')}/><Button title="Goals & preferences" icon="options-outline" secondary onPress={()=>go('Targets')}/><Button title="Add a real menu" icon="document-text-outline" secondary onPress={()=>go('Menu')}/><Button title="Privacy & data" icon="shield-checkmark-outline" secondary onPress={()=>go('Privacy')}/><Button title="Support & feedback" icon="chatbubble-outline" secondary onPress={()=>report(null)}/>
    <View style={s.profileBlock}><View style={s.between}><Text style={s.fieldLabel}>Location access</Text><Text style={s.fieldLabel}>{locationStatus}</Text></View><Button title={locating?'Finding location…':'Use my location'} secondary disabled={locating} icon="navigate-outline" onPress={()=>void locate()}/><Button title="Device permission settings" secondary onPress={()=>void Linking.openSettings().catch(()=>setMessage('Open Settings on your device to manage permissions.'))}/><Text style={s.small}>The launch area is Hamburg Zentrum. Your device location is used only when you request it.</Text></View>{!ready&&<Button title="Retry loading preferences" secondary onPress={()=>void restore()}/>}
   </>}
   {(['History','Menu','Report','Privacy','Support'] as Screen[]).includes(screen)&&<><Pressable accessibilityRole="button" accessibilityLabel="Back to Profile" onPress={()=>go('Profile')} style={s.back}><Icon name="chevron-back" size={25}/></Pressable><Text accessibilityRole="header" style={s.title}>{screen==='History'?'Your meal history':screen==='Menu'?'Add a menu':screen==='Privacy'?'Privacy & data':screen==='Support'?'Support & feedback':'Report a correction'}</Text></>}
   {screen==='History'&&<HistoryScreen activity={activity} saving={saving||!ready} onUpdate={changeHistory} onRemove={removeEntry} onOpen={openMeal} onReport={report}/>}
   {screen==='Menu'&&<MenuCapture place={place} mealType={targets.mealType} saving={saving||!ready} onSave={addMenu}/>}
   {(screen==='Report'||screen==='Support')&&<ReportScreen key={reportMeal?.id??'general'} meal={reportMeal} reports={activity.reports} saving={saving||!ready} onSave={saveReport}/>}
   {screen==='Privacy'&&<><Text style={s.sectionTitle}>Your data stays with you</Text><Text style={s.body}>Goals, favourites, entered menus, feedback and meal history are stored on this device. Photos are copied into this app’s storage. They are not uploaded to MacroMize or synced with the website.</Text><Text style={[s.sectionTitle,{marginTop:24}]}>When you use the map</Text><Text style={s.body}>Area searches send your typed address to OpenStreetMap’s Nominatim service. Map tiles request the visible area from Apple and OpenTopoMap. Directions open Apple Maps with the restaurant location. These services receive your network address. Photo text recognition downloads code and language files from jsDelivr; the photo is processed on this device.</Text><Text style={[s.sectionTitle,{marginTop:24}]}>Permissions</Text><Text style={s.body}>Location and camera access are requested when you use them. Choose a photo through the system picker; no full photo-library access is required.</Text><Button title="Manage device permissions" secondary onPress={()=>void Linking.openSettings()}/><Text style={[s.sectionTitle,{marginTop:24}]}>Take your data with you</Text><Text style={s.body}>Export your records as a JSON file. Photos can be shared separately from each entry in Meal history.</Text><Button title="Export my records" secondary disabled={!ready} onPress={()=>void exportData()}/><Button title="Delete my data from this device" secondary disabled={saving||!ready} onPress={eraseData}/></>}
   {screen==='Help'&&<>
    <Pressable accessibilityRole="button" accessibilityLabel="Back to Home" onPress={()=>go('Home')} style={s.back}><Icon name="chevron-back" size={25}/></Pressable>
    <View style={s.helpHeading}><View style={{flex:1}}><Text accessibilityRole="header" style={s.title}>What do you{'\n'}need today?</Text></View><Image source={mascot} style={s.mizeSmall}/></View>
    <View style={s.intentGrid}>{intents.map((i,index)=><Pressable key={i.title} accessibilityRole="button" accessibilityState={{selected:selectedIntent===index}} onPress={()=>chooseIntent(index)} style={[s.intent,selectedIntent===index&&s.intentSelected]}><Text style={s.intentText}>{i.title}</Text><Icon name={selectedIntent===index?'checkmark':'arrow-forward'} size={18}/></Pressable>)}</View>
    <Text style={s.label}>Or describe it in your own words</Text><TextInput accessibilityLabel="Describe your goal" multiline value={goal} onChangeText={setGoal} maxLength={500} placeholder="I’ve just finished a workout…" placeholderTextColor={C.muted} style={[s.input,{minHeight:82,textAlignVertical:'top'}]}/><Button title="Find a direction" secondary disabled={!goal.trim()} onPress={helpFromWords}/>
    {selectedIntent!==null&&<View style={s.direction}><Text style={s.eyebrow}>YOUR STARTING POINT</Text><Text style={s.directionTitle}>{intents[selectedIntent].description}</Text><Text style={s.small}>A qualitative direction based on known menu information. You can add numerical limits if you want.</Text></View>}
    <Button title="Set meal preferences" icon="arrow-forward" disabled={selectedIntent===null} onPress={()=>go('Targets')}/>
   </>}
   {screen==='Saved'&&<><Text accessibilityRole="header" style={s.title}>Your favourites</Text><View style={s.chips}>{(['Meals','Restaurants'] as const).map(v=><Chip key={v} label={v} selected={savedView===v} onPress={()=>setSavedView(v)}/>)}</View>{savedView==='Meals'?(meals.some(m=>saved.includes(m.id))?meals.filter(m=>saved.includes(m.id)).map(mealRow):<Empty icon="heart-outline" title="Your favourites start here." body="Save a meal you like and come back to it when you’re hungry." action={<Button title="Explore meals" icon="arrow-forward" onPress={()=>go('Map')}/>}/>):activity.savedRestaurants.length?activity.savedRestaurants.map(key=>{const restaurantMeals=meals.filter(m=>restaurantKey(m)===key);return <View key={key} style={s.direction}><Text style={s.directionTitle}>{restaurantMeals[0]?.restaurant??'Saved restaurant'}</Text>{restaurantMeals.map(mealRow)}<Button title="Remove restaurant favourite" secondary disabled={saving||!ready} onPress={()=>void persist(targets,saved,{...activity,savedRestaurants:activity.savedRestaurants.filter(id=>id!==key)})}/></View>;}):<Empty icon="restaurant-outline" title="Places worth coming back to." body="Save a restaurant from a dish’s details."/>}</>}
   {screen==='Meal'&&selectedMeal&&<>
    {selectedMeal.imageUrl?<View><Image source={{uri:selectedMeal.imageUrl}} style={s.dishImage}/><Pressable accessibilityRole="button" accessibilityLabel="Back to results" onPress={()=>go('Map')} style={s.imageBack}><Icon name="arrow-back" size={22}/></Pressable></View>:<Pressable accessibilityRole="button" accessibilityLabel="Back to results" onPress={()=>go('Map')} style={[s.back,{marginLeft:20}]}><Icon name="chevron-back" size={25}/></Pressable>}
    <View style={s.detailBody}><View style={s.between}><View style={{flex:1}}><Text accessibilityRole="header" style={s.dishTitle}>{selectedMeal.name}</Text><Text style={s.body}>{selectedMeal.restaurant}</Text></View>{detailMatch?.score!=null&&<View style={s.detailScore}><Text style={[s.scoreText,{fontSize:30}]}>{detailMatch.score}</Text><Text style={s.detailScoreLabel}>MATCH</Text></View>}</View>
     <View style={s.macros}>{[[selectedMeal.calories,'kcal'],[selectedMeal.protein,'protein (g)'],[selectedMeal.carbs,'carbs (g)'],[selectedMeal.fat,'fat (g)']].map(([v,label])=><View key={String(label)} style={s.macro}><Text style={s.macroValue}>{selectedMeal.nutritionStatus==='unknown'?'—':v??'—'}</Text><Text style={s.macroLabel}>{label}</Text></View>)}</View>
     <View style={s.direction}><Text style={s.directionTitle}>Why this matches you</Text>{(detailMatch?.reasons??['Set your location and targets to see your match.']).map(reason=><View key={reason} style={s.reasonRow}><Icon name={/unavailable|above|below|estimated|unconfirmed|Set your/.test(reason)?'information-circle-outline':'checkmark'} size={17}/><Text style={s.reason}>{reason}</Text></View>)}<Text style={s.small}>Match Score is a decision aid, not a scientific measurement.</Text></View>
     <Text style={s.sectionTitle}>Ingredients</Text><Text style={s.body}>{selectedMeal.ingredients?.join(', ')||'Ingredient information is unknown.'}</Text>
     <Text style={[s.sectionTitle,{marginTop:24}]}>Nutrition</Text><Text style={s.body}>{selectedMeal.provenance==='user'?'Added by you · not independently verified':selectedMeal.nutritionStatus==='verified'?'Published by the restaurant':selectedMeal.nutritionStatus==='estimated'?`Estimated · ${selectedMeal.confidence??'Unknown'} confidence`:'Nutrition information is unknown.'}</Text>
     {selectedMeal.assumptions&&<Text style={s.small}>{selectedMeal.assumptions}</Text>}{selectedMeal.menuUrl?<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.menuUrl)}><Text style={s.sourceLink}>Original restaurant menu ↗</Text></Pressable>:<><Text style={s.sourceLink}>{selectedMeal.sourceKind==='photo'?'Original menu photo':'Original menu text'}</Text>{selectedMeal.sourceKind==='photo'&&selectedMeal.sourceReference&&<Image source={{uri:selectedMeal.sourceReference}} accessibilityLabel="Original menu photo" style={{width:'100%',height:220,resizeMode:'contain'}}/>}{selectedMeal.evidenceText&&<Text style={s.body}>{selectedMeal.evidenceText}</Text>}</>}{selectedMeal.sourcePhotoUri&&selectedMeal.sourceKind!=='photo'&&<Image source={{uri:selectedMeal.sourcePhotoUri}} accessibilityLabel="Original menu photo" style={{width:'100%',height:220,resizeMode:'contain',marginTop:12}}/>}{selectedMeal.nutritionSource&&<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.nutritionSource!)}><Text style={s.sourceLink}>Nutrition source ↗</Text></Pressable>}
     <Text style={s.small}>{openingInfo(selectedMeal).label}</Text>{selectedMeal.openingHours&&<Pressable accessibilityRole="link" onPress={()=>void openLink(selectedMeal.openingHours!.sourceUrl)}><Text style={s.sourceLink}>Published opening hours ↗</Text></Pressable>}<Text style={s.small}>Checked {new Date(selectedMeal.checkedAt).toLocaleDateString()}. {selectedMeal.available===null?'Current availability is unknown.':'Confirm current availability with the restaurant.'}</Text>{selectedMeal.price&&<Text style={[s.body,{marginTop:12}]}>{selectedMeal.price}</Text>}<Button title={saved.includes(selectedMeal.id)?'Saved meal':'Save meal'} icon={saved.includes(selectedMeal.id)?'heart':'heart-outline'} secondary disabled={saving||!ready} onPress={()=>void toggleSaved()}/><Button title={activity.savedRestaurants.includes(restaurantKey(selectedMeal))?'Restaurant saved':'Save restaurant'} icon="restaurant-outline" secondary disabled={saving||!ready} onPress={()=>void toggleRestaurant()}/><Button title="Report incorrect information" secondary onPress={()=>report(selectedMeal)}/>
    </View>
   </>}
  </ScrollView>}
  {message!==''&&<Text accessibilityRole="alert" accessibilityLiveRegion="polite" style={s.globalNotice}>{message}</Text>}{screen==='Profile'&&locationError!==''&&<Text accessibilityRole="alert" style={s.globalNotice}>{locationError}</Text>}
  {screen==='Targets'&&<SafeAreaView edges={['bottom']} style={s.actionDock}><Button title={saving?'Saving…':'Find my meals'} icon="arrow-forward" disabled={saving||!ready} onPress={()=>void submitTargets()}/></SafeAreaView>}
  {screen==='Meal'&&selectedMeal&&<SafeAreaView edges={['bottom']} style={s.actionDock}><View style={s.actionRow}><View style={{flex:1.35}}><Button title="Get directions" onPress={()=>void openLink(`https://maps.apple.com/?daddr=${selectedMeal.lat},${selectedMeal.lon}&dirflg=w`)}/></View><View style={{flex:1.35}}><Button title="Choose this meal" secondary disabled={saving||!ready} onPress={()=>void chooseSelected()}/></View></View></SafeAreaView>}
  </KeyboardAvoidingView>
  {showNavigation&&<SafeAreaView edges={['bottom']} style={s.navSafe}><View style={s.nav}>{navigation.map(item=><Pressable key={item.name} accessibilityRole="tab" accessibilityState={{selected:screen===item.name}} onPress={()=>go(item.name)} style={s.navItem}><Icon name={screen===item.name?item.active:item.icon} size={23} color={screen===item.name?C.green:'#818792'}/><Text style={[s.navText,screen===item.name&&{color:C.green,fontWeight:'700'}]}>{item.name}</Text></Pressable>)}</View></SafeAreaView>}
 </SafeAreaView>;
}
export default function App(){return <SafeAreaProvider><MacroMize/></SafeAreaProvider>;}
const s=StyleSheet.create({
 root:{flex:1,backgroundColor:C.bg},
 header:{height:54,paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},wordmark:{fontSize:23,fontWeight:'700',letterSpacing:-.8,color:C.green},headerProfile:{height:44,width:36,alignItems:'center',justifyContent:'center'},
 content:{paddingHorizontal:22,paddingTop:8,paddingBottom:26,maxWidth:500,width:'100%',alignSelf:'center'},homeContent:{paddingTop:10,paddingBottom:10},
 hero:{fontSize:46,lineHeight:48,fontWeight:'800',letterSpacing:-2.1,color:C.ink,marginTop:8,marginBottom:20},heroCompact:{fontSize:41,lineHeight:43,marginTop:4,marginBottom:15},subtitle:{fontSize:16,lineHeight:24,color:C.muted,maxWidth:350},
 greeting:{flexDirection:'row',alignItems:'center',gap:8,marginTop:18,marginBottom:12,minHeight:171},greetingCompact:{marginTop:10,marginBottom:9,minHeight:141},mize:{width:140,height:169,resizeMode:'contain'},mizeCompact:{width:124,height:141},mizeSmall:{width:87,height:106,resizeMode:'contain'},bubble:{flex:1,backgroundColor:C.white,borderRadius:22,paddingVertical:18,paddingHorizontal:18,marginBottom:32},bubbleText:{fontSize:16,lineHeight:22,color:C.ink},bubbleTail:{position:'absolute',bottom:-14,left:24,width:0,height:0,borderLeftWidth:0,borderRightWidth:21,borderTopWidth:20,borderRightColor:'transparent',borderTopColor:C.white},
 entry:{flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:18,paddingVertical:19,backgroundColor:C.white,borderRadius:16,marginBottom:12,minHeight:88},entryTitle:{fontSize:17,fontWeight:'600',color:C.ink,letterSpacing:-.45,marginBottom:5},entryBody:{fontSize:13,lineHeight:19,color:C.muted},guestNote:{fontSize:11,color:C.muted,textAlign:'center',marginTop:0,marginBottom:0},
 pressed:{opacity:.75},disabled:{opacity:.4},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.6,color:C.muted,marginTop:0,marginBottom:10},title:{fontSize:35,lineHeight:39,fontWeight:'700',color:C.ink,letterSpacing:-1.6,marginBottom:24,marginTop:8},body:{fontSize:15,lineHeight:23,color:C.muted},small:{fontSize:12,lineHeight:18,color:C.muted,marginTop:8},back:{height:48,width:48,alignItems:'flex-start',justifyContent:'center',marginLeft:-5,marginBottom:10},
 button:{minHeight:54,borderRadius:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12,paddingVertical:15,paddingHorizontal:16,marginTop:18,borderWidth:1},primary:{backgroundColor:C.green,borderColor:C.green},secondary:{backgroundColor:'#EEF0E9',borderColor:'#EEF0E9'},buttonText:{fontSize:16,fontWeight:'600',color:C.white},
 numberGrid:{gap:13},numberCard:{paddingHorizontal:22,paddingVertical:16,borderRadius:15,backgroundColor:C.white},fieldLabel:{fontSize:15,fontWeight:'400',color:C.ink},numberRow:{flexDirection:'row',alignItems:'center',gap:12,marginTop:7},numberInput:{flex:1,minWidth:0,fontSize:32,fontWeight:'500',letterSpacing:-1,color:C.ink,padding:0},unit:{fontSize:14,color:C.muted,fontWeight:'400'},label:{fontSize:15,fontWeight:'500',color:C.ink,marginTop:21,marginBottom:12},
 mealTypes:{flexDirection:'row',gap:7},mealType:{flex:1,alignItems:'center',justifyContent:'center',gap:9,paddingVertical:12,backgroundColor:'#F0F1EB',borderWidth:1,borderColor:'transparent',borderRadius:13,minHeight:79},mealTypeSelected:{backgroundColor:C.white,borderColor:C.green},mealTypeText:{fontSize:12,color:C.ink},radiusHeading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:23,marginBottom:3},radius:{fontSize:15,color:C.ink},slider:{width:'100%',height:40},
 chips:{flexDirection:'row',gap:8,flexWrap:'wrap'},chip:{paddingHorizontal:15,paddingVertical:12,borderRadius:11,backgroundColor:C.white,borderWidth:1,borderColor:'transparent'},chipSelected:{backgroundColor:C.green,borderColor:C.green},chipText:{fontSize:13,color:C.ink,fontWeight:'500'},input:{fontSize:15,lineHeight:22,backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:12,padding:14,color:C.ink,minHeight:50},
 profileBlock:{borderTopWidth:1,borderColor:C.line,marginTop:30,paddingTop:24},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},helpHeading:{flexDirection:'row',alignItems:'center'},intentGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:10},intent:{width:'48%',flexGrow:1,minHeight:76,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'space-between',padding:15,borderWidth:1,borderColor:C.line,borderRadius:13,backgroundColor:C.white},intentSelected:{backgroundColor:'#EDF5D7',borderColor:'#6F8D45'},intentText:{fontSize:14,fontWeight:'600',color:C.ink,flex:1,lineHeight:20},
 direction:{backgroundColor:C.soft,padding:19,borderRadius:15,marginTop:22,marginBottom:22},directionTitle:{fontSize:17,fontWeight:'600',lineHeight:24,color:C.ink,marginBottom:10},notice:{fontSize:14,lineHeight:21,backgroundColor:'#EDF1DD',color:'#42572F',padding:15,borderRadius:12,marginTop:16},globalNotice:{fontSize:13,lineHeight:19,backgroundColor:'#EDF1DD',color:'#42572F',paddingVertical:12,paddingHorizontal:20},
 discovery:{flex:1,backgroundColor:C.bg},searchBox:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:C.white,borderRadius:29,paddingLeft:18,paddingRight:6,minHeight:56},searchInput:{flex:1,fontSize:15,minHeight:54,color:C.ink},searchAction:{width:42,height:44,alignItems:'center',justifyContent:'center'},mapTop:{position:'absolute',top:12,left:16,right:16},areaCaption:{alignSelf:'flex-start',maxWidth:'100%',backgroundColor:C.white,fontSize:12,color:C.muted,paddingHorizontal:12,paddingVertical:7,borderRadius:13,marginTop:8},mapError:{fontSize:13,lineHeight:19,color:C.green,backgroundColor:C.white,padding:12,borderRadius:13,marginTop:8},mapBottom:{position:'absolute',left:16,right:16,bottom:6,gap:12},mapAttribution:{alignSelf:'stretch',backgroundColor:'#FFFFFFED',paddingHorizontal:6,paddingVertical:3,borderRadius:4},mapAttributionText:{fontSize:10,lineHeight:13,color:'#46534A',textAlign:'center'},locateButton:{alignSelf:'flex-start',width:52,height:52,borderRadius:26,backgroundColor:C.white,alignItems:'center',justifyContent:'center',marginBottom:1},segment:{backgroundColor:'#F8F9F4',borderRadius:29,padding:7,flexDirection:'row'},segmentItem:{flex:1,alignItems:'center',justifyContent:'center',minHeight:40,paddingVertical:9,borderRadius:22,backgroundColor:'#EFF0EA'},segmentActive:{backgroundColor:C.green},segmentText:{fontSize:15,color:C.ink,fontWeight:'500'},
 mapScore:{backgroundColor:'#EEF4B9',width:54,height:54,borderRadius:27,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:C.white},mapScoreSelected:{backgroundColor:C.green,width:74,height:74,borderRadius:37},mapScoreText:{fontSize:26,color:C.green,fontWeight:'700',letterSpacing:-1},mapScoreLabel:{fontSize:8,color:C.green,letterSpacing:.5},compactState:{backgroundColor:C.white,borderRadius:18,padding:18},compactStateHeading:{flexDirection:'row',gap:10,alignItems:'center'},compactStateTitle:{fontSize:17,fontWeight:'600',lineHeight:22,color:C.ink,flexShrink:1},compactStateBody:{fontSize:13,lineHeight:20,color:C.muted,marginTop:7},inlineAction:{fontSize:14,fontWeight:'600',color:C.green,paddingTop:12},closestNotice:{fontSize:12,lineHeight:18,padding:12,backgroundColor:C.white,borderRadius:12,color:C.green},
 preview:{flexDirection:'row',gap:12,backgroundColor:C.white,borderRadius:18,padding:12,alignItems:'center'},previewImage:{width:77,height:98,borderRadius:11},previewNumbers:{fontSize:13,lineHeight:18,color:C.ink,marginTop:10,paddingTop:9,borderTopWidth:1,borderColor:C.line},listTop:{paddingHorizontal:16,paddingTop:12,gap:14},listContent:{paddingHorizontal:20,paddingTop:25,paddingBottom:24},listTitle:{fontSize:23,lineHeight:28,fontWeight:'700',letterSpacing:-.9,color:C.ink,marginBottom:18},
 sectionTitle:{fontSize:17,fontWeight:'600',color:C.ink,marginBottom:7},empty:{backgroundColor:C.white,borderRadius:18,padding:24,marginTop:8},emptyTitle:{fontSize:24,lineHeight:28,fontWeight:'600',letterSpacing:-.7,color:C.ink,marginTop:18,marginBottom:12},navSafe:{backgroundColor:C.bg,borderTopWidth:1,borderTopColor:'#E8EBE2'},nav:{flexDirection:'row',justifyContent:'space-around',paddingTop:10,paddingBottom:7},navItem:{alignItems:'center',gap:5,minWidth:66,paddingVertical:3},navText:{fontSize:11,color:'#818792'},
 mealRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:18,borderBottomWidth:1,borderColor:C.line},mealThumb:{width:76,height:92,borderRadius:12},mealTitle:{fontSize:15,fontWeight:'600',lineHeight:20,color:C.ink,letterSpacing:-.3},mealSub:{fontSize:13,lineHeight:19,color:C.muted,marginTop:3},mealMeta:{fontSize:11,lineHeight:16,color:C.muted,marginTop:5},rowEnd:{alignItems:'center',gap:12},score:{height:44,width:44,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:'#EEF4B9'},scoreText:{fontSize:20,fontWeight:'700',color:C.ink},
 detailContent:{paddingHorizontal:0,paddingTop:0,maxWidth:600},detailBody:{paddingHorizontal:20,paddingTop:18},dishImage:{width:'100%',height:300,resizeMode:'cover'},imageBack:{position:'absolute',top:16,left:16,width:44,height:44,borderRadius:22,backgroundColor:C.white,alignItems:'center',justifyContent:'center'},dishTitle:{fontSize:26,lineHeight:30,fontWeight:'600',letterSpacing:-1,color:C.ink,marginBottom:4},detailScore:{width:75,height:75,borderRadius:38,backgroundColor:'#EEF4B9',alignItems:'center',justifyContent:'center'},detailScoreLabel:{fontSize:10,color:C.ink,marginTop:1},macros:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderColor:C.line,marginTop:18,paddingTop:18},macro:{alignItems:'center',flex:1},macroValue:{fontSize:23,fontWeight:'600',letterSpacing:-.8,color:C.ink},macroLabel:{fontSize:12,lineHeight:19,color:C.muted,marginTop:5},reasonRow:{flexDirection:'row',alignItems:'flex-start',gap:8,marginBottom:6},reason:{flex:1,fontSize:14,lineHeight:21,color:C.ink},sourceLink:{fontSize:14,color:C.green,textDecorationLine:'underline',marginTop:15,marginBottom:7},actionRow:{flexDirection:'row',gap:12},actionDock:{paddingHorizontal:20,paddingTop:0,paddingBottom:12,backgroundColor:C.bg}
});
