"use client";
import { ArrowRight, ArrowLeft, Target, Leaf, House, Map as MapIcon, Heart, UserRound, LocateFixed, Search, SlidersHorizontal, Check, MapPin, Utensils, CircleHelp } from "lucide-react";
import { useEffect, useState, useRef } from "react";
import { flushSync } from "react-dom";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import MealMap from "@/components/meal-map";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Coffee, Soup, Apple } from "lucide-react";
import { defaults, intents, targetsSchema, rankMeals, restaurantKey, distanceKm, type Targets, type Meal, type Match } from "@/lib/macromize";
import {useLibrary,ModeControl,AdvancedFields,ProfileLinks,CoreScreen,MealTools,chooseMeal} from "@/components/core-features";
const nav = [{name:"Home",icon:House},{name:"Map",icon:MapIcon},{name:"Saved",icon:Heart},{name:"Profile",icon:UserRound}];
type Location = {lat:number;lon:number;name:string;current?:boolean};
export default function Home() {
 const library=useLibrary();
 const [view,setView] = useState("Home");
 const [targets,setTargets] = useState<Targets>(defaults);
 const [saved,setSaved] = useState<string[]>([]);
 const [loaded,setLoaded] = useState(false);
 const [busy,setBusy] = useState(false);
 const [message,setMessage] = useState("");
 const [intent,setIntent] = useState<number|null>(null);
 const [freeGoal,setFreeGoal] = useState("");
 const [exclusions,setExclusions] = useState("");
 const [area,setArea] = useState("");
 const [location,setLocation] = useState<Location|null>({lat:53.5503,lon:9.9920,name:"Hamburg Zentrum · launch area"});
 const [locating,setLocating] = useState(false);
 const [locationStatus,setLocationStatus] = useState("Not requested");
 const [locationError,setLocationError] = useState("");
 const [catalog,setCatalog] = useState<Meal[]>([]);
 const [catalogStatus,setCatalogStatus] = useState("loading");
 const [selected,setSelected] = useState<Match|null>(null);
 const [preview,setPreview]=useState<Match|null>(null);
 const [mapMode,setMapMode]=useState("map");
 const lookupTime=useRef(0);
 const dirty=useRef(false);
 const heading=useRef<HTMLHeadingElement>(null);
 const stateRef=useRef(targets);stateRef.current=targets;
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error);}catch(error){console.error(error);}};
  register({name:"read_meal_targets",description:"Read the current meal targets; does not search or save.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...stateRef.current})});
  register({name:"stage_meal_targets",description:"Set and show meal targets for review. Does not search or save preferences.",inputSchema:{type:"object",properties:{calories:{type:"number",minimum:100,maximum:3000},protein:{type:"number",minimum:0,maximum:250},radius:{type:"number",minimum:.5,maximum:20},mealType:{type:"string",enum:["Breakfast","Lunch","Dinner","Snack"]},diet:{type:"string",enum:["Any","Vegetarian","Vegan"]},exclusions:{type:"array",items:{type:"string"},maxItems:20}},required:["calories","protein","radius","mealType","diet","exclusions"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const next=targetsSchema.strict().parse(input);dirty.current=true;flushSync(()=>{setTargets(next);setExclusions(next.exclusions.join(", "));setView("Your targets");});return {status:"staged",targets:next};}});
  return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{loadPreferences();loadCatalog();},[]);
 useEffect(()=>{window.scrollTo(0,0);if(view!=="Home")heading.current?.focus();},[view]);
 async function loadPreferences(){try{const r=await fetch("/api/preferences");if(!r.ok)throw new Error();const data=await r.json() as {targets:Targets;saved:string[]};const parsed=targetsSchema.parse(data.targets);if(!dirty.current){setTargets(parsed);setExclusions(parsed.exclusions.join(", "));}setSaved(data.saved);setLoaded(true);setMessage("");await library.load();}catch{setMessage("Your preferences couldn’t be loaded. You can still explore. Retry in Profile.");}}
 async function loadCatalog(){setCatalogStatus("loading");try{const r=await fetch("/api/meals");if(!r.ok)throw new Error();const data=await r.json() as {meals:Meal[];status:string};setCatalog(data.meals);setCatalogStatus(data.status);}catch{setCatalogStatus("error");}}
 function go(next:string){setMessage("");setView(next);}
 function edit<K extends keyof Targets>(key:K,value:Targets[K]){dirty.current=true;setTargets(t=>({...t,[key]:value}));}
 function currentTargets(){return {...targets,exclusions:[...new Set(exclusions.split(",").map(e=>e.trim().toLowerCase()).filter(Boolean))]};}
 async function persist(nextTargets:Targets,nextSaved:string[]){if(!loaded){setMessage("Load your preferences in Profile before saving, so existing saved meals are preserved.");return false;}setBusy(true);try{const r=await fetch("/api/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({targets:nextTargets,saved:nextSaved})});const body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error);setTargets(nextTargets);setSaved(nextSaved);setLoaded(true);return true;}catch(e){setMessage(e instanceof Error?e.message:"We couldn’t save your changes. Please try again.");return false;}finally{setBusy(false);}}
 async function findMeals(e:React.FormEvent){e.preventDefault();const parsed=targetsSchema.safeParse(currentTargets());if(!parsed.success){setMessage("Please check calories (100–3000), protein (0–250 g) and your exclusions.");return;}setTargets(parsed.data);if(!await persist(parsed.data,saved))return;setMapMode("map");setPreview(null);setView("Map");}
 function chooseIntent(index:number){dirty.current=true;setIntent(index);setTargets(t=>({...t,mode:"goal",goal:intents[index].title,calories:intents[index].calories,protein:intents[index].protein}));}
 function interpretGoal(){const value=freeGoal.toLowerCase();const index=/workout|training|sport/.test(value)?0:/protein|eiwei/.test(value)?1:/light|leicht|weniger/.test(value)?2:/full|satt/.test(value)?3:/muscle|muskel/.test(value)?4:/dinner|abend/.test(value)?5:-1;if(index<0){setMessage("Please choose the direction below that best describes your goal. You can adjust all targets next.");return;}chooseIntent(index);setMessage("Suggested direction selected. Review and adjust your meal targets next.");}
 async function searchArea(e:React.FormEvent){e.preventDefault();if(!area.trim()||Date.now()-lookupTime.current<1200)return;lookupTime.current=Date.now();setLocating(true);setLocationError("");try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(area.trim())}`,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error();const data=await r.json() as {lat:string;lon:string;display_name:string}[];if(!data.length){setLocationError("We couldn’t find that area. Try a city or a more specific address.");return;}const lat=Number(data[0].lat),lon=Number(data[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new Error();setLocation({lat,lon,name:data[0].display_name});}catch{setLocationError("Area search is unavailable. Try again or use your location.");}finally{setLocating(false);}}
 function locate(){if(!navigator.geolocation){setLocationError("Location isn’t supported. Enter an area instead.");return;}setLocating(true);setLocationError("");navigator.geolocation.getCurrentPosition(p=>{setLocation({lat:p.coords.latitude,lon:p.coords.longitude,name:"Your current location",current:true});setLocationStatus("Allowed");setLocating(false);},e=>{setLocationStatus(e.code===1?"Denied":"Unavailable");setLocationError("We couldn’t access your location. Enter an area instead.");setLocating(false);},{timeout:10000,maximumAge:60000});}
 const allCatalog=[...catalog,...library.items.flatMap(i=>i.kind==="meal"?[i.meal as Meal]:[])];
 const matches=location?rankMeals(allCatalog,targets,location).slice(0,3):[];
 const savedMeals=allCatalog.filter(m=>saved.includes(m.id));
 function openMeal(m:Meal){const match=location?rankMeals([m],{...targets,radius:20040},location)[0]:null;setSelected(match??{...m,...(m.nutritionStatus==="unknown"?{calories:null,protein:null,carbs:null,fat:null}:{}),score:null,distanceKm:location?distanceKm(location,m):0,reasons:[location?"This meal is outside your current filters. Adjust preferences to compare it.":"Set your location and targets to see your match."],exact:false});go("Meal");}
 async function saveMeal(){if(!selected)return;const next=saved.includes(selected.id)?saved.filter(id=>id!==selected.id):[...saved,selected.id];if(await persist(targets,next))setMessage(next.includes(selected.id)?"Saved. Your next good meal is one tap away.":"Removed from Saved.");}
 function fields(){return <><ModeControl targets={targets} edit={edit}/>{targets.mode==="numeric"&&<div className="number-grid"><label className="number-input">Calories for this meal<div><input aria-label="Calories for this meal" required type="number" min="100" max="3000" value={Number.isNaN(targets.calories)?"":targets.calories} onChange={e=>edit("calories",e.target.valueAsNumber)}/><span>kcal</span></div></label><label className="number-input">Protein · minimum<div><input aria-label="Minimum protein" required type="number" min="0" max="250" value={Number.isNaN(targets.protein)?"":targets.protein} onChange={e=>edit("protein",e.target.valueAsNumber)}/><span>g</span></div></label></div>}<div className="field-grid"><div className="field meal-type-field"><label id="meal-type-label">Meal type</label><RadioGroup aria-labelledby="meal-type-label" value={targets.mealType} onValueChange={v=>edit("mealType",v as Targets["mealType"])} className="meal-type-options">{[{name:"Breakfast",icon:Coffee},{name:"Lunch",icon:Utensils},{name:"Dinner",icon:Soup},{name:"Snack",icon:Apple}].map(({name,icon:Icon})=><label className={`meal-type-option ${targets.mealType===name?"chosen":""}`} key={name}><RadioGroupItem value={name} className="sr-only"/><Icon size={24} strokeWidth={1.65} aria-hidden="true"/><span>{name}</span></label>)}</RadioGroup></div><div className="field"><label id="diet-label">Dietary requirement</label><Select value={targets.diet} onValueChange={v=>edit("diet",v as Targets["diet"])}><SelectTrigger aria-labelledby="diet-label"><SelectValue/></SelectTrigger><SelectContent>{["Any","Vegetarian","Vegan"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div></div><div className="field radius-field"><div className="label-row"><label id="radius-label">Search radius</label><strong>{targets.radius} km</strong></div><Slider aria-labelledby="radius-label" value={[targets.radius]} min={.5} max={20} step={.5} onValueChange={v=>edit("radius",v[0])}/></div><label className="field">Ingredients to exclude<input value={exclusions} onChange={e=>{dirty.current=true;setExclusions(e.target.value);}} placeholder="e.g. peanuts, milk" maxLength={1000}/><small>Separate with commas. Meals with unconfirmed ingredient information won’t be recommended for these exclusions.</small></label><AdvancedFields targets={targets} edit={edit}/></>}
 function results(){return <div className="results"><p className="pilot-note">Hamburg Zentrum pilot · 6 dishes, 1 restaurant</p><div className="section-heading"><h2>Your top 3 nearby</h2><span>{matches.length} meals</span></div>{catalogStatus==="loading"?<p role="status">Looking for connected menus…</p>:catalogStatus==="error"?<div className="empty-state"><CircleHelp/><h3>Menus couldn’t be loaded</h3><p>Please try again in a moment.</p><button className="secondary-button" onClick={loadCatalog}>Try again</button></div>:(catalogStatus==="not_connected"&&allCatalog.length===0)?<div className="empty-state"><Utensils/><h3>Real menus are the next ingredient.</h3><p>Restaurant data isn’t connected yet. Your targets are ready — meal matches will appear here once real menus are available.</p><span className="data-label">No restaurant data connected</span><button className="text-button" onClick={()=>go("Your targets")}>Adjust my targets <ArrowRight size={16}/></button></div>:!location?<div className="empty-state"><MapPin/><h3>Where are we eating?</h3><p>Enter an area or use your location to find nearby matches.</p></div>:matches.length===0?<div className="empty-state"><Leaf/><h3>No suitable meals nearby.</h3><p>Try a larger search radius. Your dietary requirements and exclusions stay in place.</p><button className="secondary-button" onClick={()=>go("Your targets")}>Adjust search</button></div>:<>{targets.mode==="numeric"&&!matches.some(m=>m.exact)&&<p className="notice">No exact match nearby. Here are the closest options.</p>}{matches.map(m=>mealRow(m))}</>}</div>}
 function mealRow(m:Meal & {score?:number|null;distanceKm?:number}){return <button className="meal-row" key={m.id} onClick={()=>openMeal(m)}>{m.imageUrl&&<img src={m.imageUrl} alt={m.name}/>}<div><h3>{m.name}</h3><p>{m.restaurant}</p><p>{m.calories??"Unknown"} kcal · {m.protein??"Unknown"} g protein</p>{m.price&&<p className="meal-price">{m.price}</p>}<small>{m.nutritionStatus==="verified"?"Verified":m.nutritionStatus==="estimated"?"AI estimated":"Nutrition unknown"}{m.distanceKm!==undefined?` · ${m.distanceKm.toFixed(1)} km straight line`:""}</small></div>{m.score!=null&&<span className="score">{m.score}</span>}<ArrowRight size={18}/></button>}
 const bbox=location?[location.lon-.025,location.lat-.016,location.lon+.025,location.lat+.016].join(","):null;
 return <div className={`app-shell view-${view.toLowerCase().replaceAll(" ","-")}`}>
 <header className="brand-bar"><button className="wordmark" onClick={()=>go("Home")}>MacroMize<span>®</span></button><span className="edition">FIND FOOD THAT FITS.</span><button aria-label="Profile" className="icon-button" onClick={()=>go("Profile")}><UserRound size={22}/></button></header>
 <main>
 {view==="Home"&&<div className="home-grid"><section className="intro"><p className="eyebrow">YOUR GOALS. YOUR NEXT MEAL.</p><h1>Find food<br/>that fits<br/>your goals</h1><p className="subline">Find the right meals near you — based on your goals, not guesswork.</p><div className="mize-greeting"><img src="/mize.png" alt="Mize, your friendly avocado guide"/><p><strong>Hey!</strong><br/>What are we looking for today?</p></div></section><section className="entry-area" aria-label="Start your meal search"><p className="eyebrow">LET’S FIND YOUR FIT</p><button className="entry primary-entry" onClick={()=>go("Your targets")}><Target size={32}/><div><h2>I know my targets</h2><p>Set calories, protein and more.</p></div><ArrowRight/></button><button className="entry" onClick={()=>go("Help me choose")}><Leaf size={32}/><div><h2>Help me choose</h2><p>Tell us your goal, we’ll find the right meals.</p></div><ArrowRight/></button><p className="guest-note">Made for your next meal. No account needed.</p></section></div>}
 {(view==="Your targets"||view==="Profile")&&<section className="flow"><button className="back" onClick={()=>go("Home")}><ArrowLeft size={18}/> Home</button><p className="eyebrow">{view==="Profile"?"YOUR EVERYDAY DEFAULTS":"ONE MEAL. YOUR WAY."}</p><h1 tabIndex={-1} ref={heading}>{view}</h1>{view==="Profile"&&<ProfileLinks library={library} go={go}/>}<p className="subline">{view==="Profile"?"A little less setup next time. No account needed.":"Tell us what fits. We’ll take it from here."}</p><form onSubmit={view==="Profile"?async e=>{e.preventDefault();if(await persist(currentTargets(),saved))setMessage("Your preferences are saved.");}:findMeals}>{fields()}<button className="main-button" disabled={busy}>{busy?"Saving…":view==="Profile"?"Save preferences":"Find my meals"}<ArrowRight size={19}/></button></form>{view==="Profile"&&<div className="profile-meta"><p><MapPin size={18}/> Location access <strong>{locationStatus}</strong></p><button className="text-button" onClick={locate} disabled={locating}>Use my location</button>{!loaded&&<button className="text-button" onClick={loadPreferences}>Retry loading preferences</button>}<small>Preferences and saved meals are linked to this browser through a guest cookie.</small></div>}</section>}
 {view==="Help me choose"&&<section className="flow"><button className="back" onClick={()=>go("Home")}><ArrowLeft size={18}/> Home</button><div className="help-title"><div><p className="eyebrow">A LITTLE DIRECTION</p><h1 tabIndex={-1} ref={heading}>What do you<br/>need today?</h1></div><img src="/mize.png" alt="Mize"/></div><div className="intent-grid">{intents.map((item,i)=><button className={`intent ${intent===i?"chosen":""}`} key={item.title} onClick={()=>chooseIntent(i)} aria-pressed={intent===i}><span>{item.title}</span>{intent===i?<Check size={18}/>:<ArrowRight size={18}/>}</button>)}</div><div className="field free-goal"><label htmlFor="free-goal">Or describe it in your own words</label><textarea id="free-goal" rows={2} maxLength={500} value={freeGoal} onChange={e=>setFreeGoal(e.target.value)} placeholder="I’ve just finished a workout…"/><button className="text-button" disabled={!freeGoal.trim()} onClick={interpretGoal}>Find a direction <ArrowRight size={16}/></button></div>{intent!==null&&<div className="direction"><p className="eyebrow">YOUR STARTING POINT</p><h3>{intents[intent].description}</h3><p>We’ll prioritise this direction using available menu information.</p><small>You can add exact macros or other filters next.</small></div>}<button className="main-button" disabled={intent===null} onClick={()=>go("Your targets")}>Review my preferences <ArrowRight size={19}/></button></section>}
 {view==="Map"&&<section className={`discovery ${mapMode==="map"?"map-active":"list-active"}`}><h1 className="sr-only" ref={heading} tabIndex={-1}>Find meals near you</h1><div className="map-top"><form className="location-search" onSubmit={searchArea}><Search size={20}/><input aria-label="Search area" placeholder="Search this area" value={area} maxLength={250} onChange={e=>setArea(e.target.value)}/><button disabled={locating||!area.trim()} aria-label="Search this area">{locating?"…":<ArrowRight size={19}/>}</button><button type="button" aria-label="Edit search targets" onClick={()=>go("Your targets")}><SlidersHorizontal size={20}/></button></form>{locationError?<p className="notice" role="alert">{locationError}</p>:<p className="search-caption">{location?.name??"Hamburg Zentrum"}</p>}</div><Tabs value={mapMode} onValueChange={setMapMode} className="discovery-tabs"><TabsContent value="map"><div className="map-stage"><MealMap location={location} matches={matches} selectedId={preview?.id??null} onSelect={setPreview}/></div><button className="map-locate icon-button" type="button" aria-label="Use my location" disabled={locating} onClick={locate}><LocateFixed size={22}/></button></TabsContent><TabsContent value="list"><div className="list-results">{results()}</div></TabsContent><div className="map-bottom"><TabsList className="map-tabs"><TabsTrigger value="map">Map</TabsTrigger><TabsTrigger value="list">List</TabsTrigger></TabsList>{mapMode==="map"&&<>{preview?<div className="selected-meal-preview">{mealRow(preview)}</div>:(catalogStatus==="not_connected"&&allCatalog.length===0)?<div className="map-data-note"><Utensils size={24}/><div><h2>Real menus are on the way.</h2><p>Restaurant data isn’t connected yet. Your targets are ready.</p></div></div>:!location?<div className="map-data-note"><MapPin size={24}/><div><h2>Where are we eating?</h2><p>Search an area above or use your location.</p></div></div>:catalogStatus==="loading"?<div className="map-data-note" role="status">Loading connected menus…</div>:catalogStatus==="error"?<div className="map-data-note"><p>Menus couldn’t be loaded.</p><button className="text-button" onClick={loadCatalog}>Try again</button></div>:matches.length===0?<div className="map-data-note"><div><h2>No suitable meals nearby.</h2><button className="text-button" onClick={()=>go("Your targets")}>Adjust search</button></div></div>:<div className="map-data-note"><p>Select a Match Score on the map.</p></div>}</>}</div></Tabs></section>}
 {["History","Menus","Privacy","Support","Report"].includes(view)&&<CoreScreen key={view} view={view} library={library} go={go} selected={selected} location={location} targets={targets} onAdded={m=>{openMeal(m);}}/>}
 {view==="Saved"&&<section className="flow"><p className="eyebrow">GOOD FINDS, KEPT CLOSE</p><h1 tabIndex={-1} ref={heading}>Saved meals</h1>{library.items.filter(i=>i.kind==="restaurant").length>0&&<div className="saved-restaurants"><h2>Favourite restaurants</h2>{library.items.filter(i=>i.kind==="restaurant").map(i=>i.kind==="restaurant"&&<div key={i.id}><strong>{i.name}</strong><button className="text-button" onClick={()=>{setLocation({lat:i.lat,lon:i.lon,name:i.name});go("Map");}}>See nearby meals</button><button className="text-button" onClick={()=>void library.remove(i)}>Remove</button></div>)}</div>}{savedMeals.length?savedMeals.map(m=>mealRow(m)):<div className="empty-state saved-empty"><Heart size={35}/><h3>Your favourites start here.</h3><p>Save a meal you like and come back to it when you’re hungry.</p><button className="main-button" onClick={()=>go("Map")}>Explore meals <ArrowRight size={18}/></button></div>}</section>}
 {view==="Meal"&&selected&&<section className="flow meal-detail"><button className="back" onClick={()=>go("Map")}><ArrowLeft size={18}/> Results</button>{selected.imageUrl&&<img className="dish-image" src={selected.imageUrl} alt={selected.name}/>}<div className="dish-heading"><div><h1 tabIndex={-1} ref={heading}>{selected.name}</h1><p className="subline">{selected.restaurant}</p>{selected.fitLabel&&<p className="data-label">{selected.fitLabel}</p>}</div>{selected.score!==null&&<div className="score large">{selected.score}<small>MATCH</small></div>}</div><div className="macro-values">{[[selected.calories,"kcal"],[selected.protein,"protein (g)"],[selected.carbs,"carbs (g)"],[selected.fat,"fat (g)"]].map(([value,label])=><div key={String(label)}><strong>{value??"—"}</strong><small>{label}</small></div>)}</div><section className="direction"><h3>Why this matches you</h3>{selected.reasons.map(reason=><p key={reason}><Check size={17}/> {reason}</p>)}<small>Match Score is a decision aid based on your targets, not a scientific measurement.</small></section><div className="detail-section"><h3>Ingredients</h3><p>{selected.ingredients?.join(", ")||"Ingredient information is unknown."}</p><h3>Nutrition</h3><p>{selected.nutritionStatus==="verified"?(selected.sourceKind==="user-menu"?"Entered by you from the menu":"Published by the restaurant"):selected.nutritionStatus==="estimated"?`${selected.estimationMethod==="ai"?"AI estimate":"Estimate"} · ${selected.confidence??"Unknown"} confidence`:"Nutrition information is unknown."}</p>{selected.assumptions&&<p>{selected.assumptions}</p>}{selected.nutritionSource&&<a href={selected.nutritionSource} target="_blank" rel="noreferrer">Nutrition source</a>}<p><a href={selected.menuUrl||selected.sourcePhoto||"#"} target="_blank" rel="noreferrer">Original menu source</a> · Checked {selected.checkedAt}</p>{selected.price&&<p>{selected.price}</p>}<small>{selected.openingHours?"Opening times follow the restaurant’s published weekly schedule; exceptions and current dish availability should be checked with the restaurant.":"Opening hours and current availability are unknown."}</small></div><MealTools meal={selected} library={library} go={go} saved={saved.includes(selected.id)} onSave={saveMeal}/><div className="detail-actions"><a className="main-button" href={`https://www.google.com/maps/dir/?api=1&destination=${selected.lat},${selected.lon}&travelmode=walking`} target="_blank" rel="noreferrer">Get directions</a><button className="secondary-button" disabled={library.busy||!library.loaded} onClick={async()=>{if(await chooseMeal(selected,library))go("History");}}>Choose this meal</button></div></section>}
 {library.error&&<p className="feedback" role="alert">{library.error}</p>}{message&&<p className="feedback" role="status">{message}</p>}
 {view==="Profile"&&locationError&&<p className="feedback" role="alert">{locationError}</p>}
 </main><nav className="bottom-nav" aria-label="Main navigation">{nav.map(({name,icon:Icon})=><button key={name} aria-current={view===name?"page":undefined} className={view===name?"active":""} onClick={()=>go(name)}><Icon size={24} strokeWidth={1.65} aria-hidden="true"/><span>{name}</span></button>)}</nav></div>;
}
